apiVersion: v1
kind: Secret

metadata:
  name: certs

data:
  opensearchCA.crt: {{ required ".Values.ca.crt.sap missing" .Values.ca.crt.sap | quote }}
  ca.crt: {{ required ".Values.ca.crt.digikey missing" .Values.ca.crt.digikey | quote }}
