apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rest-cert
  namespace: hermes
spec:
  dnsNames:
  - 'opensearch-hermes.{{ .Values.global.region }}.cloud.sap'
  issuerRef:
    group: certmanager.cloud.sap
    kind: DigicertIssuer
    name: digicert-issuer
  secretName: rest-cert-manager
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
