groups:
  - name: netapp-harvest-poller
    rules:
      - alert: NetappHarvestPollerTargetStatus
        expr: netapp_metadata_target_status == 1
        for: 15m
        labels:
          context: netapp-exporter
          no_alert_on_absence: "true"
          service: exporter
          severity: info
          support_group: compute-storage-api
          tier: storage
        annotations:
          summary:  Netapp Harvest poller's target status is 1
          description: Filer target can not be reached. Reach out storage team to investigate.
