groups:
  - name: netapp-harvest-workers
    rules:
      - alert: NetappHarvestCinderNeedsMoreWorkers
        expr: netapp_harvest_cinder_discovered_count - on () group_left count (netapp_metadata_exporter_count{app_kubernetes_io_instance="netapp-harvest-exporter-cinder"})
        for: 15m
        labels:
          context: netapp-exporter
          no_alert_on_absence: "true"
          service: exporter
          severity: info
          support_group: compute-storage-api
          tier: storage
        annotations:
          summary:  Netapp Harvest (Cinder) does not have enough workers
          description: Deployment netapp-harvest-exporter-cinder needs more workers. Increase at least [[ $value ]] wokers.
      - alert: NetappHarvestCinderFreeWorkersLow
        expr:  {{ .Values.apps.cinder.workerCount }} - netapp_harvest_cinder_discovered_count < 3
        for: 15m
        labels:
          context: netapp-exporter
          no_alert_on_absence: "true"
          service: exporter
          severity: info
          support_group: compute-storage-api
          tier: storage
        annotations:
          summary:  Netapp Harvest (Cinder) has less than 3 free workers
          description: Deployment netapp-harvest-exporter-cinder has only [[ $value ]] free workers. Consider increase deployment replica to {{ (mul (add (div .Values.apps.cinder.workerCount 5) 1) 5) }}.
