# The
#ingress:
#  tls_client_auth:
#    ca_cert:

disco:
  rbac:
    create: true
    serviceAccountName: disco

kube-fip-controller:
  enabled: false

ccauth:
  enabled: false

cert-manager:
  installCRDs: true
  image:
    repository: keppel.eu-de-1.cloud.sap/ccloud/cert-manager-controller
    tag: v1.6.0-p1
  webhook:
    image:
      repository: keppel.eu-de-1.cloud.sap/ccloud-quay-mirror/jetstack/cert-manager-webhook
  cainjector:
    image:
      repository: keppel.eu-de-1.cloud.sap/ccloud-quay-mirror/jetstack/cert-manager-cainjector
    extraArgs:
    - --leader-elect=false
  startupapicheck:
    image:
      repository: keppel.eu-de-1.cloud.sap/ccloud-quay-mirror/jetstack/cert-manager-ctl
  ingressShim:
    defaultIssuerName: digicert-issuer
    defaultIssuerKind: DigicertIssuer
    defaultIssuerGroup: certmanager.cloud.sap
  prometheus:
    enabled: true
  podAnnotations:
    prometheus.io/targets: kubernetes

digicert-issuer:
  enableLeaderElection: "false"

ingress-nginx-internet:
  enabled: false

# For now enabled via regional values.
maintenance-controller:
  enabled: false
