apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "archer.fullname" . }}-etc
  labels:
    app.kubernetes.io/name: {{ include "archer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  archer.ini: |
    {{ include (print .Template.BasePath "/etc/_archer.ini.tpl") . | nindent 4 }}
  policy.json: |
    {{ include (print .Template.BasePath "/etc/_policy.json.tpl") . | nindent 4 }}
