  name: error-pages
  namespace: elektra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: error-pages
  template:
    metadata:
      labels:
        app: error-pages
    spec:
      containers:
        - image: keppel.eu-de-1.cloud.sap/ccloud/juno-error-pages/default-backend:latest
          imagePullPolicy: Always
          name: error-pages
          ports:
            - containerPort: 80
              protocol: TCP