enabled: false
app_env: "production"
image: ipmi-exporter
image_tag: DEFINED_BY_PIPELINE
replicas: 2
fullnameOverride: ipmi-exporter
listen_port: 9290
ironic:
  enabled: DEFINED-IN-REGION
netbox:
  enabled: DEFINED-IN-REGION

resources: 
  requests:
    memory: 250Mi
    cpu: 800m
  limits:
    memory: 500Mi
    cpu: 1600m

aggregations:
  enabled: true
  prometheus: infra-collector

alerts:
  enabled: true
  prometheus: infra-collector