{{- if .Values.prometheus_collector.enabled -}}
apiVersion: v1
kind: Secret

metadata:
  name: k8s-additional-scrape-config
  labels:
    prometheus: kubernetes

data:
  scrape-config.yaml: {{ include (print $.Template.BasePath  "/_prometheus-scrape.yaml.tpl") . | b64enc }}
{{- end -}}
