apiVersion: v1
kind: ConfigMap

metadata:
  name: limes

data:
  domain.rego: |
{{ .Files.Get "files/domain.rego" | indent 4 }}
  project.rego: |
{{ .Files.Get "files/project.rego" | indent 4 }}
  policy.yaml: |
{{ .Files.Get "files/policy.yaml" | indent 4 }}
  limes.yaml: |
    cluster_id: ccloud
{{ toYaml .Values.limes.clusters.ccloud | indent 4 }}
  constraints-ccloud.yaml: |
{{ toYaml .Values.limes.constraints.ccloud | indent 4 }}
