apiVersion: v1
kind: Secret
metadata:
  name: limes-secret
data:
  os_password: {{ required ".Values.limes.passwords.ccloud.os_password" .Values.limes.passwords.ccloud.os_password | b64enc }}
  postgres_password: {{ required ".Values.postgresql.postgresPassword" .Values.postgresql.postgresPassword | b64enc }}
  rabbitmq_password: {{ required ".Values.limes.passwords.ccloud.rabbitmq_password" .Values.limes.passwords.ccloud.rabbitmq_password | b64enc }}
