apiVersion: v1
kind: Service

{{- $values := .Values.arista_exporter -}}

metadata:
  name: {{ include "fullName" . }}
  namespace: {{ $values.namespace }}
  labels:
    app: {{ include "fullName" . }}
    system: infra_monitoring
    type: exporter
    release: {{ include "fullName" . }}

spec:
  selector:
    app: {{ include "fullName" . }}
    type: exporter
  ports:
    - name: metrics
      port: {{ required "listen_port missing in arista_exporter values" $values.listen_port }}
