region: __DEFINED_AS_ARG__
apod:
lg_image:

registry:

lg_config_path: px-info_communities/

looking_glass:
  lg:
    proxy_port:
    authenticate: false
    subdomain: px
  lgadmin:
    authenticate: true
    proxy_port:
    subdomain: pxadmin