modules:
  f5archer:
    walk:
      - ltmVirtualServStatClientCurConns
      - ltmVirtualServStatClientMaxConns
      - ltmVsStatusAvailState
      - ltmPoolMbrStatusAvailState
      - sysCmFailoverStatusStatus
      - sysCmSyncStatusColor
      - sysCmSyncStatusStatus
      - sysGlobalTmmStatMemoryTotalKb
      - sysGlobalTmmStatMemoryUsedKb
      - sysGlobalHostOtherMemTotalKb
      - sysGlobalHostOtherMemUsedKb
      - sysGlobalHostSwapTotalKb
      - sysGlobalHostSwapUsedKb
      - sysMultiHostCpuUsageRatio5s
      - sysMultiHostCpuUsageRatio1m
      - sysProductVersion
      - sysHostDiskPartition
      - sysHostDiskBlockSize
      - sysHostDiskTotalBlocks
      - sysHostDiskFreeBlocks
      - sysStatClientCurConns
      - sysStatServerCurConns
      - sysName
      - sysSystemUptimeInSec
