modules:
  f5physical:
    walk:
      - sysGlobalTmmStatMemoryTotalKb
      - sysGlobalTmmStatMemoryUsedKb
      - sysGlobalHostOtherMemTotalKb
      - sysGlobalHostOtherMemUsedKb
      - sysGlobalHostSwapTotalKb
      - sysGlobalHostSwapUsedKb
      - sysMultiHostCpuUsageRatio5s
      - sysMultiHostCpuUsageRatio1m
      - sysProductVersion
      - sysHostDiskPartition
      - sysHostDiskBlockSize
      - sysHostDiskTotalBlocks
      - sysHostDiskFreeBlocks
      - sysSystemUptimeInSec
      - sysInterfaceName
      - sysInterfaceMediaActiveSpeed
      - sysInterfaceStatus
      - sysInterfaceStatBytesIn
      - sysInterfaceStatBytesOut
      - sysInterfaceStatDropsIn
      - sysInterfaceStatDropsOut
      - sysInterfaceStatCollisions
      - sysName
