modules:
  pxdlrouteriosxe:
    walk:
     - cpmCPULoadAvg15min
     - cpmCPULoadAvg1min
     - cpmCPULoadAvg5min
     - cpmCPUMemoryFree
     - cpmCPUMemoryUsed
     - cpmCPUTotal1minRev
     - cpmCPUTotalPhysicalIndex
     - entPhysicalName
     - entPhysicalDescr
     - cseSysCPUUtilization
     - mplsL3VpnVrfPerfCurrNumRoutes
    lookups:
      - source_indexes: [entPhysicalIndex]
        lookup: entPhysicalName
      - source_indexes: [entPhysicalIndex]
        lookup: entPhysicalDescr
    overrides:
      mplsL3VpnVrfName:
        type: DisplayString
      entPhyscalName:
        ignore: true
      cpmCPUTotalPhysicalIndex:
        ignore: true
