modules:
  pxdlrouteriosxe:
    walk:
     - cpmCPULoadAvg15min
     - cpmCPULoadAvg1min
     - cpmCPULoadAvg5min
     - cpmCPUMemoryFree
     - cpmCPUMemoryUsed
     - cpmCPUTotal1minRev
     - cpmCPUTotalPhysicalIndex
     - cseSysCPUUtilization
     - mplsL3VpnVrfPerfCurrNumRoutes
    overrides:
      mplsL3VpnVrfName:
        type: DisplayString
