apiVersion: v2
appVersion: "1.0"
description: Kube-System relevant Service collection for greenhouse clusters
name: kube-system-greenhouse
version: 1.0.1
home: https://github.com/sapcc/helm-charts/tree/master/system/kube-system-scaleout
dependencies:
  - name: cc-rbac
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.7
  - name: disco
    repository: https://charts.eu-de-2.cloud.sap
    version: 2.0.2
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.1.1
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: 1.7.3
  - name: digicert-issuer
    repository: https://charts.eu-de-2.cloud.sap
    version: 2.2.2
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.0
  - name: owner-label-injector
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.0.6
