# The
#ingress:
#  tls_client_auth:
#    ca_cert:

disco:
  rbac:
    create: true
    serviceAccountName: disco

cert-manager:
  installCRDs: true
  image:
    repository: keppel.eu-de-1.cloud.sap/ccloud/cert-manager-controller
    tag: v1.5.5-p1
  webhook:
    image:
      repository: keppel.eu-de-1.cloud.sap/ccloud-quay-mirror/jetstack/cert-manager-webhook
  cainjector:
    image:
      repository: keppel.eu-de-1.cloud.sap/ccloud-quay-mirror/jetstack/cert-manager-cainjector
    extraArgs:
    - --leader-elect=false
  startupapicheck:
    image:
      repository: keppel.eu-de-1.cloud.sap/ccloud-quay-mirror/jetstack/cert-manager-ctl
  ingressShim:
    defaultIssuerName: digicert-issuer
    defaultIssuerKind: DigicertIssuer
    defaultIssuerGroup: certmanager.cloud.sap
  prometheus:
    enabled: true
  podAnnotations:
    prometheus.io/targets: kubernetes
  extraArgs:
    - --enable-certificate-owner-ref=true

digicert-issuer:
  enableLeaderElection: "false"

owner-info:
  support-group: containers
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/system/kube-system-scaleout
