kind: Deployment
apiVersion: apps/v1

metadata:
  name: manila-scheduler
  labels:
    system: openstack
    type: backend
    component: manila
    alert-tier: os
    alert-service: manila
spec:
  replicas: {{ .Values.pod.replicas.scheduler }}
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: manila-scheduler
  template:
    metadata:
      labels:
        name: manila-scheduler
      annotations:
        configmap-etc-hash: {{ include (print .Template.BasePath "/etc-configmap.yaml") . | sha256sum }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - manila-scheduler
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
      initContainers:
        - name: fetch-rabbitmqadmin
          image: {{.Values.global.dockerHubMirror}}/library/busybox
          command: ["/scripts/fetch-rabbitmqadmin.sh"]
          volumeMounts:
            - name: manila-bin
              mountPath: /scripts
              readOnly: true
            - name: etcmanila
              mountPath: /shared
      containers:
        - name: manila-scheduler
          image: {{.Values.global.registry}}/loci-manila:{{.Values.loci.imageVersion}}
          imagePullPolicy: IfNotPresent
          command:
            - dumb-init
            - kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "manila-scheduler --config-file /etc/manila/manila.conf"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "{{ .Release.Name }}-mariadb,{{ .Release.Name }}-rabbitmq"
            {{- if .Values.sentry.enabled }}
            - name: SENTRY_DSN_SSL
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: manila.DSN
            - name: SENTRY_DSN
              value: $(SENTRY_DSN_SSL)?verify_ssl=0
            {{- end }}
          livenessProbe:
            exec:
              command: ["/etc/manila/rabbitmqadmin", "-H", "manila-rabbitmq", "-u", "admin", "-p" , "{{ .Values.rabbitmq.users.admin.password }}", "list", "bindings", "|", "grep", "manila-scheduler"]
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 20
          readinessProbe:
            exec:
              command:
              - grep
              - 'ready'
              - /etc/manila/probe
            timeoutSeconds: 3
            periodSeconds: 5
            initialDelaySeconds: 5
          volumeMounts:
            - name: etcmanila
              mountPath: /etc/manila
            - name: manila-etc
              mountPath: /etc/manila/manila.conf
              subPath: manila.conf
              readOnly: true
            - name: manila-etc
              mountPath: /etc/manila/policy.yaml
              subPath: policy.yaml
              readOnly: true
            - name: manila-etc
              mountPath: /etc/manila/logging.ini
              subPath: logging.ini
              readOnly: true
          {{- if .Values.pod.resources.scheduler }}
          resources:
{{ toYaml .Values.pod.resources.scheduler | indent 13 }}
          {{- end }}
      hostname: manila-scheduler
      volumes:
        - name: etcmanila
          emptyDir: {}
        - name: manila-bin
          configMap:
            name: manila-bin
            defaultMode: 0555
        - name: manila-etc
          configMap:
            name: manila-etc
