apiVersion: v1
description: cc3test - for blackbox testing the CC+1
name: cc3test
version: 0.1.0
maintainers:
  - name: Abhishek Kumar (I332028)
  - name: Martin Vossen (D021500)
dependencies:
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.2