apiVersion: v1
description: A Helm chart for ELK-stack
name: elk
version: 0.2.1
home: https://github.com/sapcc/helm-charts/tree/master/system/elk
dependencies:
  - name: es-master
    alias: es_master
    repository: file://vendor/es-master
    version: 2.0.0
    condition: es_master.enabled

  - name: es-client
    alias: es_client
    repository: file://vendor/es-client
    version: 2.0.0
    condition: es_client.enabled

  - name: es-data
    alias: es_data
    repository: file://vendor/es-data
    version: 2.0.1
    condition: es_data.enabled

  - name: es-manager
    alias: es_manager
    repository: file://vendor/es-manager
    version: 2.0.0
    condition: es_manager.enabled

  - name: kibana
    repository: file://vendor/kibana
    version: 2.0.0
    condition: kibana.enabled

  - name: fluent
    repository: file://vendor/fluent
    version: 2.0.1
    condition: fluent.enabled

  - name: fluent-systemd
    alias: fluent_systemd
    repository: file://vendor/fluent-systemd
    version: 2.0.0
    condition: fluent_systemd.enabled

  - name: fluent-prometheus
    alias: fluent_prometheus
    repository: file://vendor/fluent-prometheus
    version: 1.0.0
    condition: fluent_prometheus.enabled

  - name: fluent-scaleout
    alias: fluent_scaleout
    repository: file://vendor/fluent-scaleout
    version: 1.0.0
    condition: fluent_scaleout.enabled

  - name: wall-e
    alias: wall_e
    repository: file://vendor/wall-e
    version: 2.0.0
    condition: wall_e.enabled

  - name: logstash-external
    alias: logstash_external
    repository: file://vendor/logstash-external
    version: 1.0.0
    condition: logstash_external.enabled

  - name: k8s-event-logger
    alias: k8s_event_logger
    condition: k8s_event_logger.enabled
    repository: https://kuckkuck.github.io/k8s-event-logger
    version: 1.0
