apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    prometheus: openstack
  name: prometheus-maia-oprom
  namespace: maia
spec:
  podMetricsEndpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    path: federate
    port: web
    scheme: http
    scrapeTimeout: 25s
    params:
      match[]:
        - '{__name__="up"}'
  jobLabel: prometheus-maia-oprom-2
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
        - prometheus
