apiVersion: v1
kind: Secret

metadata:
  name: cc3test-secrets
stringData: # TODO: reformat `stringData:` into `data:` (stringData is okay from k8s perspective, but helm-diff has trouble with it, see <https://github.com/databus23/helm-diff/issues/302>)
  secrets.yaml: |
    secrets:
{{ toYaml .Values.secrets | indent 6 }}
    authentication:
{{ toYaml .Values.authentication | indent 6 }}
    ldapUrl: {{ .Values.ldapUrl }}
    ldapUser: {{ .Values.ldapUser }}
    ldapPassword: {{ .Values.ldapPassword }}
    ldapSuffix: {{ .Values.ldapSuffix }}
    tsig_key_name: {{ .Values.tsig_key_name }}
    tsig_key: {{ .Values.tsig_key }}
