# Default values for manila-antelope.
manila-antelope:
  alerts:
    enabled: false
  coordinationBackendMountPath: manila
  netapp_volume_name_template: "share_ante_%(share_id)s"
  netapp_vserver_name_template: "ma_ante_%s"
  pod:
    replicas:
      api: 1
      scheduler: 1
    health:
      use_agent: false
  seeds:
    all_enabled: false
    endpoint_prefix: antelope-
    service_type: share-antelope