replicaCount: 2
image:
  repository: sapcc/maintenance-controller
  tag: "0.20.0"
  pullPolicy: IfNotPresent
rbac:
  create: false
  serviceAccountName: default
config: null
flatcar-linux-update-agent:
  enabled: true
esx:
  enabled: false
  config: null
kubernikus:
  enabled: false
  config: null
  cloudconfig: cloud-config
limits:
  cpu: 200m
  memory: 256Mi
tolerations: null
owner-info:
  support-group: containers
  service: maintenance-controller
  maintainers:
    - Erik Schubert
    - Fabian Ruff
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/system/maintenance-controller
