apiVersion: v2
description: A Helm chart for the operated global Prometheus for monitoring infrastructure.
name: prometheus-infra
version: 1.0.4
maintainers:
  - name: Tommy Sauer (viennaa)
  - name: Martin Vossen (artherd42)
dependencies:
  - name: prometheus-server-pre7
    alias: prometheus-infra-global
    repository: https://charts.eu-de-2.cloud.sap
    version: 6.4.6
