apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: velero-credentials
data:
  OS_AUTH_URL: {{ required ".Values.velero.openstack.osAuthUrl missing" .Values.velero.openstack.osAuthUrl | b64enc }}
  OS_PASSWORD: {{ required ".Values.velero.openstack.osPassword missing" .Values.velero.openstack.osPassword | b64enc }}
  OS_USERNAME: {{ required ".Values.velero.openstack.osUsername missing" .Values.velero.openstack.osUsername | b64enc }}
  OS_PROJECT_NAME: {{ required ".Values.velero.openstack.osProjectName missing" .Values.velero.openstack.osProjectName | b64enc }}
  OS_REGION_NAME: {{ required ".Values.velero.openstack.osRegionName missing" .Values.velero.openstack.osRegionName | b64enc }}
  OS_DOMAIN_NAME: {{ required ".Values.velero.openstack.osDomainName missing" .Values.velero.openstack.osDomainName | b64enc }}
