apiVersion: v2
name: prometheus-vmware
version: 1.2.3
description: Prometheus VMware Monitoring and Metrics Collection
dependencies:
  - name: prometheus-server-test
    repository: https://charts.eu-de-2.cloud.sap
    version: 7.0.13
    alias: prometheus-server
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.2
