apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: {{ include "alertmanager.fullname" . }}-alertmanager.alerts
  labels:
    alertmanager: {{ include "alertmanager.name" . }}
    prometheus: infra-frontend

spec:
{{ include (print .Template.BasePath "/alerts/_alertmanager.alerts.tpl") . | indent 2 }}
