apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pgmetrics-etc
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  custom-metrics.yaml: |
{{ toYaml .Values.customMetrics | indent 4}}
