{{- range $appName, $appValues := .Values.apps }}
{{- with $ }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netapp-harvest.fullname" . }}-{{ $appName }}-sd
spec:
  selector:
    app.kubernetes.io/instance: {{ include "netapp-harvest.fullname" . }}-{{ $appName }}-sd
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netapp-harvest.fullname" . }}-{{ $appName }}
spec:
  selector:
    app.kubernetes.io/instance: {{ include "netapp-harvest.fullname" . }}-{{ $appName }}
  ports:
  - name: http
    protocol: TCP
    port: 13000
    targetPort: 13000
---
{{- end }}
{{- end }}
