apiVersion: v1
kind: ConfigMap

metadata:
  name: hubcopter

data:
  hubcopter.yaml: |
    concourseDomain: https://ci1.eu-de-2.cloud.sap
    excludedRegions:
      - eu-ru-1
    swiftPrefixes:
      - services/backup
      - services/billing
      - services/castellum
      - services/content-replication
      - services/gatekeeper
      - services/keppel
      - services/less-ops-more-dev # hubcopter
      - services/limes
      - services/swift
      - services/tenso
    excludedSwiftPrefixes:
      # moved from metal to scaleout
      - services\/backup\/backup-cleanup_[^s].*
      - services\/content-replication\/backup-replication_[^s].*
      - services\/content-replication\/content-repo_[^s].*
      - services\/gatekeeper\/doop-central-kubernikus_[^s].*
      - services\/gatekeeper\/doop-central_[^s].*
    regionQuality:
{{ toYaml .Values.hubcopter.regionQuality | indent 6 }}
