{{- if .Values.logger.enabled }}
kind: Deployment
apiVersion: apps/v1

metadata:
  name: neutron-nsxv3-logstash
  labels:
    system: openstack
    type: backend
    component: neutron
spec:
  replicas: {{ .Values.logger.logstash.replicas | default 3 }}
  revisionHistoryLimit: {{ .Values.pod.lifecycle.upgrades.deployments.revision_history }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: neutron-nsxv3-logstash
  template:
    metadata:
      labels:
        name: neutron-nsxv3-logstash
      annotations:
        configmap-logger-hash: {{ include (print .Template.BasePath "/configmap-nsxv3-logstash.yaml") . | sha256sum }}
    spec:
      containers:
        - name: neutron-nsxv3-logstash
          image: {{.Values.global.dockerHubMirror}}/library/logstash:{{.Values.imageVersionLogstash | required "Please set neutron.imageVersionLogstash"}}
          env:
          - name: XPACK_MONITORING_ENABLED
            value: "false"
          ports:
          - containerPort: 5514
          volumeMounts:
          - mountPath: /usr/share/logstash/pipeline/logstash.conf
            subPath: pipeline.conf
            name: logger-config
      volumes:
        - name: logger-config
          configMap:
            name: neutron-nsxv3-logstash
            items:
            - key: pipeline
              path: pipeline.conf
{{- end -}}
