apiVersion: v2
appVersion: "1.0"
description: Helm audit management for Openstack
maintainers:
  - name: notque
name: hermes
version: 0.0.4
dependencies:
  - alias: rabbitmq_notifications
    condition: audit.enabled
    name: rabbitmq
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.5.1
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.0
  - name: elasticsearch-hermes
    alias: elasticsearch_hermes
    repository: file://vendor/elasticsearch-hermes
    version: 0.0.3
    condition: elasticsearch_hermes.enabled
  - name: elasticsearch-hermes-kibana
    alias: elasticsearch_hermes_kibana
    repository: file://vendor/elasticsearch-hermes-kibana
    version: 0.0.1
    condition: elasticsearch_hermes_kibana.enabled
  - name: opensearch
    alias: opensearch_hermes
    condition: opensearch_hermes.enabled
    repository: https://opensearch-project.github.io/helm-charts
    version: 2.14.1
  - name: opensearch-dashboards
    alias: opensearch_hermes_dashboards
    condition: opensearch_hermes_dashboards.enabled
    repository: https://opensearch-project.github.io/helm-charts
    version: 2.12.0
