dependencies:
  - alias: rabbitmq_notifications
    condition: audit.enabled
    name: rabbitmq
    repository: file://../../common/rabbitmq
    version: 0.3.2
  - name: utils
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.3.4
