apiVersion: v2
name: snmp-exporter-apod
version: 0.1.0
description: Prometheus snmp-exporter
maintainers:
  - name: Olaf Heydorn (D042653)

dependencies:
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.2
