{{- if .Values.opensearch_hermes.enabled }}
apiVersion: v1
kind: Secret

metadata:
  name: security-config

data:
  config.yml: {{ include (print .Template.BasePath  "/opensearch/_config.yml.tpl") . | b64enc }}
  internal_users.yml: {{ include (print .Template.BasePath  "/opensearch/_internal_users.yml.tpl") . | b64enc }}
  roles.yml: {{ include (print .Template.BasePath  "/opensearch/_roles.yml.tpl") . | b64enc }}
  roles_mapping.yml: {{ include (print .Template.BasePath  "/opensearch/_roles_mapping.yml.tpl") . | b64enc }}
  action_groups.yml: {{ include (print .Template.BasePath  "/opensearch/_action_groups.yml.tpl") . | b64enc }}
  tenants.yml: {{ include (print .Template.BasePath  "/opensearch/_tenants.yml.tpl") . | b64enc }}
  whitelist.yml: {{ include (print .Template.BasePath  "/opensearch/_whitelist.yml.tpl") . | b64enc }}
  nodes_dn.yml: {{ include (print .Template.BasePath  "/opensearch/_nodes_dn.yml.tpl") . | b64enc }}
  audit.yml: {{ include (print .Template.BasePath  "/opensearch/_audit.yml.tpl") . | b64enc }}
  user: {{ .Values.users.promuser.username | b64enc}}
  password: {{ .Values.users.promuser.password | b64enc }}
{{- end }}
