{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: apic-exporter
  namespace: {{ .Values.exporter.namespace }}
  labels:
    prometheus: {{ required ".Values.exporter.prometheus.name" .Values.exporter.prometheus.name }}

spec:
  jobLabel: apic-exporter

  selector:
    matchLabels:
      app: apic-exporter

  # Find pods in any namespace.
  namespaceSelector:
    matchNames:
      - {{ .Values.exporter.namespace }}

  endpoint:
    - interval: {{ .Values.exporter.prometheus.scrapeInterval }}
      scrapeTimeout: {{ .Values.exporter.prometheus.scrapeTimeout }}
      port: metrics
      scheme: http
      relabelings:
        - action: labelmap
          regex: '__meta_kubernetes_service_label_(.+)'
        - targetLabel: job
          replacement: apic-exporter
{{- end -}}