kind: Service
apiVersion: v1
metadata:
  name: apic-exporter
  namespace: {{ .Values.exporter.namespace }}
  labels:
    app: apic-exporter

spec:
  selector:
    app: apic-exporter
  ports:
    - name: metrics
      port: {{ .Values.exporter.prometheus.port }}
