apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app.kubernetes.io/managed-by: thanos-admin
    app.kubernetes.io/name: query
    traefik.ingress.kubernetes.io/service.serversscheme: https
  name: thanos-admin-query-test
  namespace: thanos
spec:
  ports:
  - name: grpc
    port: 10901
    protocol: TCP
    targetPort: grpc
  - name: http
    port: 10902
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/managed-by: thanos-admin
    app.kubernetes.io/name: query
  sessionAffinity: None
  type: ClusterIP
