{{- if .Values.metisAPI.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metis-api
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ include "metisAPI.chart" $ }}
    app.kubernetes.io/instance: {{ template "name" . }}
    app.kubernetes.io/component: "api"
    app.kubernetes.io/part-of: "metis"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    prometheus: {{ .Values.alerts.prometheus }}
spec:
  jobLabel: metis
  selector:
    matchLabels:
      app.kubernetes.io/name: metis-api
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  podMetricsEndpoints:
    - interval: 60s
      scrapeTimeout: 55s
      port: http
      path: {{ .Values.metisAPI.metrics.path }}

{{- end }}
