{{- if .Values.metisAPI.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: metis-api-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ include "metisAPI.chart" $ }}
    app.kubernetes.io/instance: {{ template "name" . }}
    app.kubernetes.io/component: "api"
    app.kubernetes.io/part-of: "metis"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  metisRonlyPW: {{ required "missing MetisDB ronly pw" .Values.metis.ronlyPassword | b64enc }}
  metisServicePW: {{ required "missing .Values.metisAPI.service_password" .Values.metisAPI.service_password | b64enc }}
{{- end }}
