{{- if .Values.metisAPI.enabled }}

apiVersion: v1
kind: Service
metadata:
  name:  metis-api
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ include "metisAPI.chart" $ }}
    app.kubernetes.io/instance: {{ template "name" . }}
    app.kubernetes.io/component: "api"
    app.kubernetes.io/part-of: "metis"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/component: "api"
  ports:
  - name: http
    port: {{ .Values.metisAPI.port }}
    protocol: TCP

{{- end }}
