apiVersion: v2
description: blackbox-tests-integrity - performs Integrity checks for Converged Cloud
name: blackbox-tests-integrity
version: 0.1.1
maintainers:
  - name: Abhishek Kumar
  - name: Martin Vossen
dependencies:
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.2
