kind: Service
apiVersion: v1
metadata:
  name: vrops-inventory
  namespace: {{ required ".Values.vrops.namespace variable missing" $.Values.vrops.namespace }}
spec:
  selector:
    app: vrops-inventory
  ports:
    - name: metrics
      port: {{ .Values.vrops.inventory.port_number }}
