{{- if .Values.admission.enabled }}
apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: vpa-admission
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: vpa-admission
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  dnsNames:
    - vpa-webhook.{{ .Release.Namespace }}.svc
    - vpa-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: vpa-admission
  secretName: vpa-admission-tls-certs
{{ end -}}
