apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: openstack-jaeger
spec:

  ingress:
    enabled: true
    annotations:
      disco: "true"
      kubernetes.io/tls-acme: "true"
    hosts:
      - tracing.{{ .Values.global.region }}.cloud.sap
    tls:
      - hosts:
        - tracing.{{ .Values.global.region }}.cloud.sap
        secretName: tls-tracing-{{ .Values.global.region }}-cloud-sap

  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://elk-elasticsearch.scaleout.{{ .Values.global.region }}.cloud.sap:443
        index-prefix: os-jaeger
    secretName: openstack-jaeger
    esIndexCleaner:
      enabled: true
      numberOfDays: 14
      schedule: "59 23 * * *"
