apiVersion: v1
kind: Secret
metadata:
  name: openstack-jaeger
data:
  ES_USERNAME: {{ .Values.global.elk_elasticsearch_jaeger_user | required ".global.elk_elasticsearch_jaeger_user" }}
  ES_PASSWORD: {{ .Values.global.elk_elasticsearch_jaeger_password | required ".global.elk_elasticsearch_jaeger_password" }}
