apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: database
type: Opaque
data:
  postgres-password:  {{ .Values.postgresPassword | required ".Values.postgresPassword" | b64enc | quote }}
  backup-password:    {{ .Values.backup.os_password | required ".Values.backup.os_password" | b64enc | quote }}
