global:
  registryAlternateRegion: test

selector:   true 
toleration: false 

podsubnet: true

globalRegion:
  enabled: false

images:
  parrot:
    repository: sapcc/kube-parrot
    tag: v202005061106

# as: 12345
metricPort: 30039
bgpNeighborCount: 2

# Deploy kube-proxy Prometheus alerts.
alerts:
  enabled: true
  # Name of the Prometheus to which the alerts should be assigned to.
  # Can be a comma-separated list.
  prometheus: kubernetes

imagePullSecrets: []
# - name: secretName

owner-info:
  support-group: containers
  maintainers:
    - Marian Schwarz
    - Dmitri Fedotov
    - Michael Schmidt
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/system/kube-parrot
