owner-info:
  support-group: observability
  maintainers:
    - Tommy Sauer
    - Richard Tief
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/system/prometheus-kubernetes

prometheus-server:
  name: kubernetes

  retentionTime: 7d

  persistence:
    enabled: true
    size: 100Gi

  thanos:
    enabled: false
