apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vpa-butler
  name: vpa-butler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vpa-butler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vpa-butler
    spec:
      containers:
      - image: {{ required ".Values.image.repository missing" .Values.image.repository }}:{{ required ".Chart.AppVersion missing" .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        name: vpa-butler
        resources:
          limits:
            cpu: 200m
            memory: 150Mi
          requests:
            cpu: 150m
            memory: 100Mi
      serviceAccountName: vpa-butler
