global:
  keystoneNamespace: keystone
  region: xx-yy-1
  tld: example.org
  dockerHubMirror: registry.example.com/dockerhub
  registry: registry.example.com
  registryAlternateRegion: registry-other.example.com
  quayIoMirror: registry.example.com/quayio

keppel:
  image_tag: '12345'
  trivy:
    hostname: trivy.example.com
    token: Sup3rS3cret

postgresql:
  postgresPassword: keks

pgbackup:
  swift:
    os_password: securePassword

pgmetrics:
  db_password: keks
