global:
  keystoneNamespace: keystone
  region: xx-yy-1
  tld: example.org
  dockerHubMirror: registry.example.com/dockerhub
  quayIoMirror: registry.example.com/quayio

keppel:
  image_tag: '12345'

postgresql:
  postgresPassword: keks
pgmetrics:
  db_password: keks
