apiVersion: v2
name: thanos-metal
description: Deploy Thanos via operator 
type: application
version: 0.0.4
dependencies:
  - name: thanos
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.5
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.0
