thanos:
  name: metal
  deployWholeThanos: false
  ingress:
    enabled: true
    hosts:
      - thanos-metal
  grpcIngress:
    enabled: true
    hosts:
      - thanos-metal
      - metrics.metal
  queryDiscovery: true
