
installCRDs: false
image:
  registry: keppel.eu-de-1.cloud.sap/ccloud-k8sgcr-mirror
additionalPodAnnotations:
  prometheus.io/targets: "kubernetes"

# The recommender is always enabled.
recommender:
  image:
    repository: autoscaling/vpa-recommender
    pullPolicy: IfNotPresent
  interval: 5m

admission:
  enabled: true

updater:
  enabled: true
  image:
    # The full image will be $registry/$repository:$tag.
    repository: autoscaling/vpa-updater
    pullPolicy: IfNotPresent
