apiVersion: v2
name: thanos-global
description: Deploy Thanos via operator
type: application
version: 0.1.6
dependencies:
  - name: thanos
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.4.2
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.0
