apiVersion: v1
kind: ConfigMap
metadata:
  name: maintenance-controller
  namespace: kube-system
data: 
  maintenance.yaml: {{ tpl ( required "A maintenance configuration is required" .Values.config ) . | b64enc }}
  {{- if .Values.esx.enabled }}
  esx.yaml: {{ required "A esx maintenance configuration is required" .Values.esx.config | b64enc }}
  {{- end }}
  {{- if .Values.kubernikus.enabled }}
  kubernikus.yaml: {{ required "A kubernikus configuration is required" .Values.kubernikus.config | b64enc }}
  {{- end }}
