apiVersion: v1
kind: Secret
metadata:
  name: maintenance-controller
  namespace: kube-system
type: Opaque
data:
  {{ range $key, $val := .Values.secrets -}}
  {{ $key | quote }}: {{ $val | b64enc }}
  {{ end -}}
