{{- $root := . }}
{{- if .Values.maiaFederation.enabled }}
{{- range $target := .Values.global.targets }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    ccloud/support-group: observability
    prometheus: maia-oprom
  name: {{ include "prometheusVMware.fullName" (list $target $root) }}-maia-federation
  namespace: vmware-monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 60s
    path: federate
    port: http
    scheme: http
    scrapeTimeout: 55s
    params:
      match[]:
        - '{__name__=~"{{- include "maiaFederationMatches" $root }}",project!~"internal",vccluster!~".*management.*"}'
    metricRelabelings:
      - source_labels: [__name__, project ]
        regex: '^vrops_virtualmachine_.+;(.+)'
        replacement: '$1'
        target_label: project_id
      - regex: 'project|collector|exported_job|instance|internal_name|prometheus|resource_uuid|thanos_cluster|thanos_cluster_type|vccluster|vcenter'
        action: labeldrop
    {{- if $.Values.maiaFederation.neo.enabled }}
      - source_labels: [__name__]
        target_label: domain_id
        regex: ^vrops_hostsystem_.+
        replacement: "{{ $.Values.maiaFederation.neo.domain_id }}"
    {{- end }}

  jobLabel: {{ include "prometheusVMware.name" (list $target $root) }}
  selector:
    matchLabels:
      prometheus: {{ include "prometheusVMware.name" (list $target $root) }}
{{- end }}
{{- end }}
