replicaCount: 1

image:
  repository: keppel.eu-de-1.cloud.sap/ccloud/slack-alert-reactions
  pullPolicy: IfNotPresent

env:
  APP_ENVIRONMENT:   # { "prod" | "dev" } Defines active channels, target Repository for issues and link trigger url
  GITHUB_TOKEN:   # github user token to create issues
  SLACK_USER_TOKEN:   # Slack user token to connect with workspace
  SLACK_WORKSPACE:   # { default: "convergedcloud" } Slack workspace to connect to

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
