---
apiVersion: v2
appVersion: 2.9.0
description: A Helm chart for the NATS.io High Speed Cloud Native Distributed Communications
  Technology.
name: nats
keywords:
  - nats
  - messaging
  - cncf
version: 0.18.0
