owner-info:
  support-group: compute
  maintainers:
    - Christopher Hans
    - Maximilian Lendrich
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/prometheus-rules/prometheus-vmware-rules

# The name of the Prometheus to which the alert- and aggregation rules will be assigned to.
prometheusName: vmware

# static list to check if region is a sharded region, to be removed later
shardedRegions:
  - qa-de-1
