apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}
data:
  config.yaml: |
    region: {{ .Values.global.region }}

    netbox_url: {{ .Values.updater.netbox_url }}
    netbox_role_id: {{ .Values.updater.netbox_role_id }}
    netbox_tenant_id: {{ .Values.updater.netbox_tenant_id }}
    netbox_device_status: {{ .Values.updater.netbox_device_status }}

    lenovo_username: {{ .Values.updater.lenovo_username }}
    lenovo_password: {{ .Values.updater.lenovo_password }}
    lenovo_console: {{ .Values.updater.lenovo_console | default lxca.{{ .Values.global.region }}.cloud.sap }}

    redfish_username: {{ .Values.updater.redfish_username }}
    redfish_password: {{ .Values.updater.redfish_password }}

    connection_timeout: {{ .Values.updater.connection_timeout }}
    scrape_interval: {{ .Values.updater.scrape_interval }}
