apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}
data:
  config.yaml: |
    region: {{ .Values.global.region }}

    netbox_url: {{ .Values.updater.netbox_url }}
    netbox_role_id: {{ .Values.updater.netbox_role_id }}
    netbox_tenant_id: {{ .Values.updater.netbox_tenant_id }}
    netbox_device_status: {{ .Values.updater.netbox_device_status }}

    connection_timeout: {{ .Values.updater.connection_timeout }}

    scrape_interval: {{ .Values.updater.scrape_interval }}

