apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}
data:
  config.yaml: |
    region: {{ .Values.global.region }}

    netbox_url: {{ required ".Values.updater.netbox_url missing" .Values.updater.netbox_url | quote }}
    netbox_token: {{ required ".Values.updater.netbox_token missing" .Values.updater.netbox_token | quote }}
    netbox_role_id: {{ required ".Values.updater.netbox_role_id" .Values.updater.netbox_role_id | quote }}
    netbox_tenant_id: {{ required ".Values.updater.netbox_tenant_id" .Values.updater.netbox_tenant_id | quote }}
    netbox_device_status: {{ required ".Values.updater.netbox_device_status" .Values.updater.netbox_device_status | quote }}

    lenovo_username: {{ required ".Values.updater.lenovo_username" .Values.updater.lenovo_username | quote }}
    lenovo_password: {{ required ".Values.updater.lenovo_password" .Values.updater.lenovo_password | quote }}
    lenovo_console: {{ include "lenovo_console" . }}

    redfish_username: {{ required ".Values.updater.redfish_username" .Values.updater.redfish_username | quote }}
    redfish_password: {{ required ".Values.updater.redfish_password" .Values.updater.redfish_password | quote }}

    connection_timeout: {{ required ".Values.updater.connection_timeout" .Values.updater.connection_timeout | quote }}
    scrape_interval: {{ required ".Values.updater.scrape_interval" .Values.updater.scrape_interval | quote }}
