{{- if .Values.updater.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ required ".Values.updater.namespace missing" .Values.updater.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
spec:
  replicas: {{ required ".Values.updater.replicas missing" .Values.updater.replicas }}
  selector:
    matchLabels:
      app: {{ include "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ include "fullname" . }}

        image: {{ required ".Values.global.registry missing" .Values.global.registry }}/{{ required ".Values.updater.image.name missing" .Values.updater.image.name }}:{{ required ".Values.updater.image.tag missing" .Values.updater.image.tag  }}

        command:
          - /usr/bin/python3

        args:
          - main.py
          - -c
          - /config/config.yml
          {{- if .Values.updater.debug -}}
          {{- "- --debug" -}}
          {{- end -}}

        volumeMounts:
          - mountPath: /inventory-updater/config
            name: updater-config
            readOnly: true

        resources:
  {{ toYaml .Values.resources | indent 10 }}

      volumes:
        - name: updater-config
          configMap:
            name: {{ include "fullname" . }}
{{ end -}}
