---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastiflow-query-exporter
  labels:
    system: openstack
    service: logging
    component: configuration

data:
  elastiflow-thousandeyes-probes.cfg: |
{{ (.Files.Glob "files/*.cfg").AsConfig | indent 2 }}
