{{ if .Values.zabbix.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Release.Name }}-zabbix-tls
  labels:
    type: configuration
    component: bind
data:
  tls.ca: {{ .Values.zabbix.tls_ca }}
  tls.crt: {{ .Values.zabbix.tls_crt }}
  tls.key: {{ .Values.zabbix.tls_key }}
{{ end }}
