apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkDeprecatedApiVersion
metadata:
  name: deprecatedapiversion-k8s1.22
  labels:
    on-prod-ui: 'true'
    {{- include "sources" (tuple "deprecated-api-version" "deprecated-api-version-k8s1.22") | indent 4 }}
spec:
  enforcementAction: {{ if and (.Values.global.region | hasPrefix "qa-") (eq .Values.cluster_type "baremetal" "scaleout") -}} deny {{- else -}} dryrun {{- end }}
  match: {{ include "match_active_helm_releases" . | indent 4 }}
  parameters:
    helmManifestParserURL: {{ quote .Values.helm_manifest_parser_url }}
    kubernetesVersion: '1.22'
    apiVersions:
      - admissionregistration.k8s.io/v1beta1
      - apiextensions.k8s.io/v1beta1
      - apiregistration.k8s.io/v1beta1
      - authentication.k8s.io/v1beta1
      - authorization.k8s.io/v1beta1
      - certificates.k8s.io/v1beta1
      - coordination.k8s.io/v1beta1
      - networking.k8s.io/v1beta1
      - rbac.authorization.k8s.io/v1beta1
      - scheduling.k8s.io/v1beta1
      - storage.k8s.io/v1beta1
