apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkDeprecatedApiVersion
metadata:
  name: deprecatedapiversion-k8s1.26
  labels:
    on-prod-ui: 'true'
spec:
  enforcementAction: dryrun # set to 'deny' to enforce
  match: {{ include "match_active_helm_releases" . | indent 4 }}
  parameters:
    helmManifestParserURL: {{ quote .Values.helm_manifest_parser_url }}
    kubernetesVersion: '1.26'
    apiVersions:
      - autoscaling/v2beta2
      - flowcontrol.apiserver.k8s.io/v1beta1
