apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkDeprecatedApiVersion
metadata:
  name: deprecatedapiversion-k8s1.22
  labels:
    on-prod-ui: 'false'
spec:
  enforcementAction: dryrun # set to 'deny' to enforce
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Secret"]
    labelSelector:
      matchLabels:
        owner: helm
        status: deployed
  parameters:
    helmManifestParserURL: {{ quote .Values.helm_manifest_parser_url }}
    kubernetesVersion: '1.22'
    apiVersions:
      - admissionregistration.k8s.io/v1beta1
      - apiextensions.k8s.io/v1beta1
      - apiregistration.k8s.io/v1beta1
      - authentication.k8s.io/v1beta1
      - authorization.k8s.io/v1beta1
      - certificates.k8s.io/v1beta1
      - coordination.k8s.io/v1beta1
      - networking.k8s.io/v1beta1
      - rbac.authorization.k8s.io/v1beta1
      - scheduling.k8s.io/v1beta1
      - storage.k8s.io/v1beta1
