apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkImagesFromNonKeppel
metadata:
  name: imagesfromnonkeppel
  labels:
    on-prod-ui: 'true'
    {{- include "sources" (tuple "images-from-non-keppel" "images-from-non-keppel") | indent 4 }}
spec:
  enforcementAction: {{ if (eq .Values.cluster_type "baremetal" "scaleout") -}} deny {{- else -}} dryrun {{- end }}
  match: {{ include "match_pods_and_pod_owners" . | indent 4 }}
