apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkHelm2Releases
metadata:
  name: helm2releases
  labels:
    on-prod-ui: 'true'
    {{- include "sources" (tuple "helm2-releases" "helm2-releases") | indent 4 }}
spec:
  enforcementAction: {{ if .Values.global.region | hasPrefix "qa-" -}} deny {{- else -}} dryrun {{- end }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["ConfigMap"]
    namespaces: ["kube-system"]
    labelSelector:
      matchLabels:
        OWNER: TILLER
