{{/* we only need this policy in baremetal. Services in other clusters can scale freely */}}
{{- if eq .Values.cluster_type "baremetal" "test" -}}

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkHighCPURequests
metadata:
  name: highcpurequests
  labels:
    on-prod-ui: 'true'
spec:
  enforcementAction: dryrun
  match: {{ include "match_pods_and_pod_owners" . | indent 4 }}
  parameters:
    maxCpu: 6

{{- end -}}
