apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkImagesFromCorrectRegistry
metadata:
  name: imagesfromcorrectregistry
  labels:
    on-prod-ui: 'true'
spec:
  enforcementAction: dryrun
  match: {{ include "match_pods_and_pod_owners" . | indent 4 }}
  parameters:
    registry: {{.Values.global.registry | required ".Values.global.registry not found"}}
    registryAlternateRegion: {{.Values.global.registryAlternateRegion | required ".Values.global.registryAlternateRegion not found"}}
