apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkPrometheusScrapeAnnotations
metadata:
  name: prometheusscrapeannotations
  labels:
    on-prod-ui: 'false' # TODO: enable after testing
    {{- include "sources" (tuple "prometheus-scrape-annotations" "prometheus-scrape-annotations") | indent 4 }}
spec:
  enforcementAction: dryrun # change to "deny" to enforce
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod", "Service"]
