apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkResourceLimits
metadata:
  name: resourcelimits
  labels:
    on-prod-ui: 'true'
spec:
  enforcementAction: dryrun
  match: {{ include "match_pods_and_pod_owners" . | indent 4 }}
