apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkOutdatedImageBases
metadata:
  name: outdatedimagebases
  labels:
    on-prod-ui: 'true'
    {{- include "sources" (tuple "outdated-image-bases" "outdated-image-bases") | indent 4 }}
spec:
  enforcementAction: dryrun # change to "deny" to enforce
  match: {{ include "match_pods_only" . | indent 4 }}
  parameters:
    doopImageCheckerURL: {{ quote .Values.doop_image_checker_url }}
