apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkIngressAnnotations
metadata:
  name: ingressannotations-wrong-prefix
  labels:
    on-prod-ui: 'true'
    {{- include "sources" (tuple "ingress-annotations" "ingress-annotations-wrong-prefix") | indent 4 }}
spec:
  enforcementAction: dryrun # TODO deny
  match:
    kinds:
      - apiGroups: ["networking.k8s.io"]
        kinds: ["Ingress"]
  parameters:
    hint: 'use the prefix "ingress.kubernetes.io/" instead'
    regexes: [ "^nginx.ingress.kubernetes.io/" ] # this is the default annotations-prefix; we use a different one for backwards-compatiblity
