apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkRegionValueMissing
metadata:
  name: regionvaluemissing
  labels:
    on-prod-ui: 'true'
    {{- include "sources" (tuple "region-value-missing" "region-value-missing") | indent 4 }}
spec:
  enforcementAction: dryrun # set to "deny" to enforce
  match: {{ include "match_active_helm_releases" . | indent 4 }}
  parameters:
    helmManifestParserURL: {{ quote .Values.helm_manifest_parser_url }}
