apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkPodLabels
metadata:
  name: podlabels
  labels:
    on-prod-ui: 'true'
spec:
  enforcementAction: dryrun
  match: {{ include "match_pods_and_pod_owners" . | indent 4 }}
  parameters:
    osServices: {{.Values.osServices | required ".Values.osServices not found"}}
