{{/* This policy is disabled (except in the test suite) because we will soon rewrite it to match the new support labels. */}}
{{- if eq .Values.cluster_type "test" -}}

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkPodLabels
metadata:
  name: podlabels
  labels:
    on-prod-ui: 'true'
spec:
  enforcementAction: dryrun
  match: {{ include "match_pods_and_pod_owners" . | indent 4 }}
  parameters:
    osServices: {{.Values.osServices | required ".Values.osServices not found"}}

{{- end -}}
