{{- if .Values.network_generic_ssh_exporter.operator }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: network-generic-ssh-exporter-neutron-router
  namespace: infra-monitoring
  labels:
    prometheus: {{ .Values.network_generic_ssh_exporter.aggregations.prometheus }}
    app.kubernetes.io/name: network-generic-ssh-exporter-neutron-router
spec:
  httpSDConfigs:
    - url: {{ .Values.global.http_sd_configs.netbox_url }}/devices/?status=active&region={{ .Values.global.region }}&tenant=converged-cloud&role=neutron-router
      refreshInterval: {{ .Values.global.http_sd_configs.refresh_interval }}
  metricsPath: /ssh
  interval: 120s
  scrapeTimeout: 60s
  relabelings:
    - sourceLabels: [job]
      regex: network/ssh
      action: keep
    - sourceLabels: [__address__]
      targetLabel: __param_target
    - targetLabel: __param_batch
      replacement: neutron-router
    - targetLabel: __param_credential
      replacement: default
    - targetLabel: __param_device
      replacement: cisco-ios-xe
    - sourceLabels: [__param_target]
      targetLabel: instance
    - targetLabel: __address__
      replacement: network-generic-ssh-exporter:9116
  metricRelabelings:
    - action: labeldrop
      regex: "metrics_label"
    - sourceLabels: [__name__, server_name]
      regex: '^ssh_[A-za-z0-9]+;.*((rt|asr)[0-9]+)[a|b]$'
      replacement: '$1'
      targetLabel: asr_pair
      action: replace
{{- end }}
