{{- if .Values.ingress.enabled }}
kind: Ingress
apiVersion: networking.k8s.io/v1

metadata:
  name: plutono
  annotations:
    kubernetes.io/tls-acme: {{ default false .Values.plutono.tls | quote }}
    disco: {{ default false .Values.plutono.disco | quote }}
  {{- if .Values.plutono.auth.tls_client_auth.enabled}}
    ingress.kubernetes.io/auth-tls-secret: {{ default "" .Values.plutono.auth.tls_client_auth.secret }}
    nginx.ingress.kubernetes.io/auth-tls-secret: {{ default "" .Values.plutono.auth.tls_client_auth.secret }}
    ingress.kubernetes.io/auth-tls-verify-depth: "3"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "3"
    ingress.kubernetes.io/auth-tls-verify-client: "optional"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "optional"
  {{- end }}

spec:
  tls:
    - secretName: tls-{{ first .Values.plutono.endpoint.host.public | replace "." "-" }}
      hosts:
      {{- range $host := .Values.plutono.endpoint.host.public }}
        - {{ $host }}
      {{- end }}
  rules:
  {{- range $host := .Values.plutono.endpoint.host.public }}
    - host: {{ $host }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: plutono
              port:
                number: {{$.Values.plutono.endpoint.port.public}}
  {{- end }}
{{- if .Values.ingress.global }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1

metadata:
  name: plutono-global
  annotations:
    kubernetes.io/tls-acme: {{ default false .Values.plutono.tls | quote }}
    disco: {{ default false .Values.plutono.disco | quote }}
    disco/zone-name: "global.cloud.sap"
  {{- if .Values.plutono.auth.tls_client_auth.enabled}}
    ingress.kubernetes.io/auth-tls-secret: {{ default "" .Values.plutono.auth.tls_client_auth.secret }}
    nginx.ingress.kubernetes.io/auth-tls-secret: {{ default "" .Values.plutono.auth.tls_client_auth.secret }}
    ingress.kubernetes.io/auth-tls-verify-depth: "3"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "3"
    ingress.kubernetes.io/auth-tls-verify-client: "optional"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "optional"
  {{- end }}

spec:
  tls:
    - secretName: tls-{{ first .Values.plutono.endpoint.host.global | replace "." "-" }}
      hosts:
      {{- range $host := .Values.plutono.endpoint.host.public }}
        - {{ $host }}
      {{- end }}
  rules:
  {{- range $host := .Values.plutono.endpoint.host.public }}
    - host: {{ $host }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: plutono
              port:
                number: {{$.Values.plutono.endpoint.port.public}}
  {{- end }}
{{- end }}
{{- end }}
