kind: Deployment
apiVersion: apps/v1
metadata:
  name: tarslite
  namespace: tars
spec:
  selector:
    matchLabels:
      app: tarslite
  template:
    metadata:
      labels:
        app: tarslite
    spec:
      containers:
         - name: tarslite
           image: {{ required ".Values.global.registry missing" .Values.global.registry }}/{{ required ".Values.tarslite.image.name missing" .Values.tarslite.image.name }}:{{ required ".Values.tarslite.image.tag missing" .Values.tarslite.image.tag  }}
           ports:
             - name: webhook
               containerPort: {{ required ".Values.tarslite.webhook.port" .Values.tarslite.webhook.port }}
           command:
             - /usr/bin/python3
           args:
             - tarslite.py
           volumeMounts:
             - mountPath: /config
               name: tarslite-config
               readOnly: true
      volumes:
        - configMap:
            name: tarslite-config
          name: tarslite-config
