apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tarslite
spec:
  defaultBackend:
    service:
      name: tarslite
      port:
        name: webhook
  tls:
    - hosts: 
      - {{ .Values.tarslite.hostname }}
