apiVersion: v2
description: A Helm chart for the operated global Prometheus for monitoring Kubernetes.
name: prometheus-kubernetes-global
version: 4.0.0

dependencies:
  - name: prometheus-server
    alias: prometheus-kubernetes-global
    repository: https://charts.eu-de-2.cloud.sap
    version: 6.3.2
