apiVersion: batch/v1
kind: Job
metadata:
metadata:
  name: {{ template "fullname" . }}-delete-secrets
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      name: {{ template "fullname" . }}-delete-secrets
    spec:
      containers:
      - name: delete-secrets
        image: "{{ include "preferredRegistry" . }}/base-images/alpine-kubectl:edge-latest"
        env:
        - name: DEBUG
          value: {{ quote .Values.debug }}
        command:
          - ash
          - -c
          - |
            set -eou pipefail
            [[ -n ${DEBUG:-} ]] && set -x

            {{- range $user, $settings := .Values.users }}
            kubectl delete secret --ignore-not-found {{ $.Release.Name }}-pguser-{{ $user }}
            {{- end }}
      restartPolicy: Never
      serviceAccountName: {{ template "fullname" . }}
