{{ if .Values.enabled }}
{{- $values := .Values -}}

apiVersion: v1
kind: ConfigMap

metadata:
  name: cloudprober
  labels:
    app: cloudprober

data:
  cloudprober.cfg: |
    {{- range $i, $config := .Values.targets_icmp }}
    probe {
      type: PING
      name: "icmp-{{ $config.name }}"
      targets {
        host_names: "{{ $config.ipt }}"
      }

      {{- if $config.zone }}
      additional_label {
        key: "dst_zone"
        value: "{{ $config.zone }}"
      }
      {{- end }}


      ping_probe {
        use_datagram_socket: false
      }
      interval_msec: {{ $values.icmpIntervalMsec }}
      timeout_msec: {{ $values.icmpTimeoutMsec }}

      latency_unit: "ms"
      latency_distribution {
              explicit_buckets: "2,4,8,16,32,64,128,256,512"
      }
    }
    {{- end }}

    {{- range $i, $config := .Values.targets_http }}
    probe {
      type: HTTP
      name: "http-{{ $config.name }}"
      targets {
        host_names: "{{ $config.ip }}"
      }

     {{- if $config.zone }}
     additional_label {
       key: "dst_zone"
       value: "{{ $config.zone }}"
     }
     {{- end }}

      http_probe {
        port: {{ $config.port }}
      }

      interval_msec: {{ $values.httpIntervalMsec }}
      timeout_msec: {{ $values.httpTimeoutMsec }}

      latency_unit: "ms"
      latency_distribution {
              explicit_buckets: "2,4,8,16,32,64,128,256,512"
      }
    }
    {{- end }}

    server {
      type: HTTP
      http_server {
        port: {{ .Values.httpServerPort }}
      }
    }
    surfacer {
      type: PROMETHEUS

      prometheus_surfacer {
        metrics_prefix: "cprober_"
      }
    }

  {{ end -}}
