{{- if .Values.enabled }}
{{- $values := .Values }}

{{- range $i, $prober := .Values.probers }}
{{ if ne $i 0 }}---{{ end }}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress

metadata:
  name: cloudprober-{{$prober.zone}}
  labels:
    app: cloudprober-exporter
  annotations:
    kubernetes.io/tls-acme: {{ default false $values.ingress.tls | quote }}
    disco: {{ default false $values.ingress.disco | quote }}

spec:
  tls:
    - secretName: cloudprober-{{ $prober.zone }}
      hosts: [{{ $values.ingress.hostName_prefix }}-{{ $prober.zone }}.{{ $values.global.region }}.{{ $values.global.domain }}]
  rules:
    - host: {{ $values.ingress.hostName_prefix }}-{{ $prober.zone }}.{{ $values.global.region }}.{{ $values.global.domain }}
      http:
        paths:
        - path: /metrics
          backend:
            serviceName: cloudprober-{{ $prober.zone }}
            servicePort: 9313
        - path: /config
          backend:
            serviceName: cloudprober-{{ $prober.zone }}
            servicePort: 9313
        - path: /
          backend:
            serviceName: cloudprober-{{ $prober.zone }}
            servicePort: 1080
---
{{- end }}
{{- end }}
