kubernikus:
  imageTag: 9495540e60cb587ba2bb15560903e1f02272c555
  image: keppel.global.cloud.sap/ccloud/kubernikus

  #use a dedicated serviceaccount and proper RBAC rules for this deployment
  standalone: false
  useServiceAccount: true
  includeRBAC: true
  k8sniff:
    useRBAC: true

  api:
    policyFile: /etc/kubernikus/policy-ccadmin.json
  operator:
    nodeAffinity: false
    controllers: [groundctl, deorbiter, migration, servicing, certs]
  ingress:
    annotations:
      disco: "true"
kubernikus-dex:
  namespaceOverride: kubernikus
