{{- range $source_region, $source := .Values.source }}
apiVersion: batch/v1
kind: CronJob

metadata:
  name: backup-replication-from-{{ $source_region }}
  labels:
    component: backup-replication

spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  schedule: "59 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            component: backup-replication-from-{{ $source_region }}
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/replication-configmap.yaml") $ | sha256sum }}
            checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") $ | sha256sum }}
            {{- if and $.Values.global.linkerd_enabled $.Values.global.linkerd_requested }}
            linkerd.io/inject: enabled
            {{- end }}
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: config
            configMap:
              name: swift-http-import
          containers:
          - name: swift-http-import
            image: {{include "swift_http_import_image" $}}
            imagePullPolicy: IfNotPresent
            args:
            - /etc/swift-http-import/{{ $source_region }}.yaml
            env:
            - name: {{ $.Values.global.region | upper }}_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backup-replication-secret
                  key: {{ $.Values.global.region }}_auth_password
            - name: {{ $source_region | upper }}_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backup-replication-secret
                  key: {{ $source_region }}_auth_password
            - name: 'LOG_TRANSFERS'
              value: 'true'
            - name: 'DEBUG'
              value: {{ $.Values.swift_http_import.debug | quote }}
            {{- if not (and $.Values.global.linkerd_enabled $.Values.global.linkerd_requested) }}
            - name: LINKERD_AWAIT_DISABLED
              value: "Linkerd was not enabled or not requested"
            {{- end }}
            securityContext:
              runAsNonRoot: true
            volumeMounts:
            - name: config
              mountPath: /etc/swift-http-import
            resources:
              # observed usage in qa-de-1 during runs: CPU <= 30m, RAM up to 60 MiB
              limits:
                cpu: '50m'
                memory: '100Mi'
              requests:
                cpu: '10m'
                memory: '50Mi'
---
{{- end }}
