apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: gkimagesfromnonkeppel
spec:
  crd:
    spec:
      names:
        kind: GkImagesFromNonKeppel
      validation:
        openAPIV3Schema:
          properties: {}

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package imagesfromnonkeppel

        # This violation is usually only detectable on the
        # deployment/daemonset/statefulset level since Tugger will fix the
        # image reference on the pod level.

        violation_owners = {"Deployment", "DaemonSet", "StatefulSet"}
        pod_owners       = {"ReplicaSet", "DaemonSet", "StatefulSet"}

        pod_belongs_to[kind] {
          ref := input.review.object.metadata.ownerReferences[_]
          kind := ref.kind
          kind == pod_owners[_]
        }

        containers[container] {
          input.review.object.kind == "Pod"
          count(pod_belongs_to) == 0 # otherwise the violation will be reported on the DaemonSet or Deployment
          container := input.review.object.spec.containers[_]
        }

        containers[container] {
          input.review.object.kind == violation_owners[_]
          container := input.review.object.spec.template.spec.containers[_]
        }

        violation[{"msg": msg, "details": {"container": container_name, "image": image}}] {
          container := containers[_]
          container_name := container.name
          image := container.image

          not regex.match("^keppel\\.[^/.]*\\.cloud.sap/", image)
          msg := sprintf("container %q uses an image that is not from a Keppel registry: %s", [container_name, image])
        }
