apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: gkingressannotations
spec:
  crd:
    spec:
      names:
        kind: GkIngressAnnotations

  targets:
    - target: admission.k8s.gatekeeper.sh
      libs:
        - |
          {{ .Files.Get "lib/add-support-labels.rego" | nindent 10 }}
      rego: |
        package ingressannotations
        import data.lib.add_support_labels

        iro := input.review.object

        # These annotations have been disabled due to CVE-2021-25742
        disabled_annotations = {
          "ingress.kubernetes.io/auth-snippet",
          "ingress.kubernetes.io/configuration-snippet",
          "ingress.kubernetes.io/server-snippet",
          "ingress.kubernetes.io/modsecurity-snippet",
        }

        violation[{"msg": add_support_labels.from_k8s_object(iro, msg)}] {
          iro.kind == "Ingress"

          annotation := disabled_annotations[_]
          is_string(object.get(iro, ["metadata", "annotations", annotation], null))

          msg := sprintf("has disabled annotation: %q", [annotation])
        }
