apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: gkoutdatedimagebases
spec:
  crd:
    spec:
      names:
        kind: GkOutdatedImageBases
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          properties:
            doopImageCheckerURL:
              type: string

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package outdatedimagebases

        obj := input.review.object

        # check each pod container
        checks[{ "container": container, "response": resp }] {
          obj.kind == "Pod"
          container := obj.status.containerStatuses[_]

          # only consider images stored in Keppel since we want to inspect the X-Keppel-Min-Layer-Created-At header
          regex.match("^keppel", container.image)

          # query vulnerability status through helper API
          imgID := trim_prefix(container.imageID, "docker-pullable://")
          url := sprintf("%s/v1/headers?image=%s", [input.parameters.doopImageCheckerURL, imgID])
          resp := http.send({"url": url, "method": "GET", "raise_error": false, "timeout": "10s"})
        }

        violation[{"msg": msg}] {
          check := checks[_]
          check.response.status_code != 200

          msg := "doop-image-parser did not return HTTP status 200. Please retry in ~5 minutes."
        }

        violation[{"msg": msg}] {
          labels := object.get(obj.metadata, "labels", {})

          check := checks[_]
          check.response.status_code == 200
          createdAtAsUnixTime := to_number(trim_space(object.get(check.response.body, "X-Keppel-Min-Layer-Created-At", "Unclear")))

          # complain if it's older than one year
          nowAsUnixTime := time.now_ns() / 1000000000
          ageInSeconds := nowAsUnixTime - createdAtAsUnixTime
          ageInDays := ageInSeconds / 86400
          ageInDays > 365
          msg := sprintf(
            "support-group=%s,service=%s: image %s for container %q uses a very old base image (oldest layer is %.0f days old)",
            [object.get(labels, "support-group", "none"), object.get(labels, "service", "none"), check.container.image, check.container.name, ageInDays]
          )
        }
