apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: gkunmanagedpods
spec:
  crd:
    spec:
      names:
        kind: GkUnmanagedPods

  targets:
    - target: admission.k8s.gatekeeper.sh
      libs:
        - |
          {{ .Files.Get "lib/add-support-labels.rego" | nindent 10 }}
      rego: |
        package unmanagedpods
        import data.lib.add_support_labels

        iro := input.review.object

        violation[{"msg": add_support_labels.from_k8s_object(iro, msg)}] {
          iro.kind == "Pod"
          object.get(iro.metadata, ["ownerReferences"], []) == []
          msg := "pod is not owned by a managing construct"
        }
