apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: {{ include "fullName" . }}
{{- $values := .Values.redfish_exporter -}}

{{- if $values.enabled }}
  namespace: {{ $values.namespace }}
  labels:
    prometheus: {{ required "$values.prometheus missing" $values.prometheus }}
    app.kubernetes.io/name: {{ include "fullName" . }}

spec:
  - job_name: 'redfish/bm'
    params:
      job: [redfish/bm]
    interval: {{$values.scrapeInterval}}
    scrapeTimeout: {{$values.scrapeTimeout}}
    http_sd_configs:
      - url: {{ $values.http_sd_configs.netbox_production_url }}/devices/?custom_labels=job=redfish/bm&target=mgmt_only&status=active&role=server&tenant=converged-cloud&platform=ironic&tag__n=no-redfish&region={{ .Values.global.region }}
        refreshInterval: {{ $values.http_sd_configs.refresh_interval }}
    metrics_path: /redfish
    relabelings:
      - sourceLabels: [job]
        regex: redfish/bm
        action: keep
      - sourceLabels: [__address__]
        targetLabel: __param_target
      - sourceLabels: [__param_target]
        targetLabel: instance
      - targetLabel: __address__
        replacement: redfish-exporter:{{$values.listen_port}}

  - job_name: 'redfish/cp'
    params:
      job: [redfish/cp]
    interval: {{$values.scrapeInterval}}
    scrapeTimeout: {{$values.scrapeTimeout}}
    http_sd_configs:
      - url: {{ $values.http_sd_configs.netbox_production_url }}/devices/?custom_labels=job=redfish/cp&target=mgmt_only&status=active&role=server&tenant=converged-cloud&platform=coreos&tag__n=no-redfish&region={{ .Values.global.region }}
        refreshInterval: {{ $values.http_sd_configs.refresh_interval }}
    metrics_path: /redfish
    relabelings:
      - sourceLabels: [job]
        regex: redfish/cp
        action: keep
      - sourceLabels: [__address__]
        targetLabel: __param_target
      - sourceLabels: [__param_target]
        targetLabel: instance
      - targetLabel: __address__
        replacement: redfish-exporter:{{$values.listen_port}}
      - sourceLabels: [__meta_serial]
        targetLabel: server_serial

  - job_name: 'redfish/bb'
    params:
      job: [redfish/bb]
    interval: {{$values.scrapeInterval}}
    scrapeTimeout: {{$values.scrapeTimeout}}
    http_sd_configs:
      - url: {{ $values.http_sd_configs.netbox_production_url }}/devices/?custom_labels=job=redfish/bb&target=mgmt_only&status=active&role=server&tenant=converged-cloud&platform=vmware-esxi&tag__n=no-redfish&region={{ .Values.global.region }}
        refreshInterval: {{ $values.http_sd_configs.refresh_interval }}
    metrics_path: /redfish
    relabelings:
      - sourceLabels: [job]
        regex: redfish/bb
        action: keep
      - sourceLabels: [__address__]
        targetLabel: __param_target
      - sourceLabels: [__param_target]
        targetLabel: instance
      - targetLabel: __address__
        replacement: redfish-exporter:{{$values.listen_port}}
{{- end }}

{{- if $values.firmware.enabled }}
  - job_name: 'redfish/fw'
    params:
      job: [redfish/fw]
    interval: {{$values.firmware.scrapeInterval}}
    scrapeTimeout: {{$values.firmware.scrapeTimeout}}
    http_sd_configs:
      - url: {{ $values.http_sd_configs.netbox_production_url }}/devices/?custom_labels=job=redfish/fw&target=mgmt_only&status=active&role=server&tenant=converged-cloud&tag__n=no-redfish&region={{ .Values.global.region }}
        refreshInterval: {{ $values.http_sd_configs.refresh_interval }}
    metrics_path: /firmware
    relabelings:
      - sourceLabels: [__address__]
        targetLabel: __param_target
      - sourceLabels: [__param_target]
        targetLabel: instance
      - targetLabel: __address__
        replacement: redfish-exporter:{{$values.listen_port}}
{{- end }}
