unbound:
  image_unbound: unbound
  image_unbound_exporter: unbound_exporter
  image_unbound_tag: "20220523144459"
  image_unbound_exporter_tag: "20220523144516"
  image_pullPolicy: IfNotPresent
  port_unbound_exporter: 9107
  interface: 0.0.0.0
  failure_domain_zone: a

alerts:
  # Name of the Prometheus to which the alerts should be assigned to.
  prometheus: openstack
