unbound:

  # make sure we do pull the images
  image_pullPolicy: Always

  # it's a good idea to override with more stable tags
  unbound:
    image: unbound
    image_tag: latest

  unbound_exporter:
    image: unbound_exporter
    image_tag: latest

  dnstap:
    image: dnstap
    image_tag: latest

  port_unbound_exporter: 9167
  interface: 0.0.0.0
  failure_domain_zone: a
  ext_stats: "yes"

resources:
  unbound:
    requests:
      memory: "512Mi"
      cpu: "250m"
  metric:
    requests:
      memory: "128Mi"
      cpu: "100m"
  dnstap:
    requests:
      memory: "128Mi"
      cpu: "100m"

alerts:
  # Name of the Prometheus to which the alerts should be assigned to.
  prometheus: openstack

owner-info:
  support-group: network-api
  service: unbound
  maintainers:
    - David Hoeller
    - Benjamin Tinney
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/system/unbound
