global:
  # The OpenStack region.
  region:

  # The TLD as used in the URL.
  domain:

# Name of the Alertmanager instance. Used to deploy additional configuration via Secret.
alertmanagerName:

prometheus-alertmanager:
  # Provide Alertmanager configuration vi an existing secret in the same namespace.
  useExistingSecret: true

  # Optional ingress for this Alertmanager.
  ingress:
    enabled: true

    # Will be expanded to https://alertmanager.$region.$domain .
    host: alertmanager

  internalIngress:
    enabled: true

    # Will be expanded to https://alertmanager-internal.$region.$domain .
    host: alertmanager-internal

  alerts:
    prometheus: infra-frontend

# Values for Slack receivers.
slack:
  api:
  kubernikus:
  metal:
  network:
  vmware:
  compute:
  compute_storage_api:
  email:
  identity:
  network_api:
  observability:
  containers:

# Values for PagerDuty receivers.
pagerduty_sap:
  api:
  alertTest:
  metal:
  network:
  vmware:
  osd_mom_network:
  osd_mom_compute:
  compute:
  compute_storage_api:
  identity:
  email:
  containers:
  network_api:
  observability:

# Values for email_k8s_alerting receiver
email_k8s_alerting:
  smtp_host:
  auth_username:
  auth_password:
  email_from_address:
  # optional
  # email_bcc_to_address:
