apiVersion: v1
appVersion: wallaby
description: A Helm chart Opensatck Glance
icon: https://www.openstack.org/themes/openstack/images/project-mascots/Glance/OpenStack_Project_Glance_vertical.png
name: glance
version: 0.1.18
