dependencies:
  - name: mariadb
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.3.39
  - name: memcached
    repository:  https://charts.eu-de-2.cloud.sap
    version: 0.0.7
  - condition: mysql_metrics.enabled
    name: mysql_metrics
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.7
  - name: rabbitmq
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.12
  - name: utils
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.3.0
