dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.5.5
  - name: memcached
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.0.10
  - condition: mysql_metrics.enabled
    name: mysql_metrics
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.7
  - name: rabbitmq
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.4.2
  - name: utils
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.5.0
