apiVersion: v2
name: metis
version: 0.0.3
description: Read-only DB for replicas of OpenStack DBs and Project Masterdata
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.5.4
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.2
