namespace: metis

alerts:
  tier: "os"
  prometheus: "infra-collector"

owner-info:
  support-group: observability
  maintainers:
    - "Ivo Gosemann"
  helm-chart-url: "https://github.com/sapcc/helm-charts/tree/master/system/metis"

metisAPI:
  enabled: false
  port: 8080
  image: metis-api
  imageTag: "202207141740"
  metrics:
    enabled: true
    path: "/metrics"
  alerts:
    enabled: false
    tier: "os"
    prometheus: "infra-collector"
