global:
  registry: my.docker.registry
  dockerHubMirror: my.dockerhub.mirror
  dockerHubMirrorAlternateRegion: other.dockerhub.mirror
  metis:
    user: test
    password: test123
  ldap:
    host: localhost
    port: 2711
    ssl_skip_verify: true
    suffix: test
    group_search_base_dns: test
    bind_dn: test
logstash:
  elastic:
    password: test123
