global:
  region:
  domain:

disco:
  rbac:
    create: true
    serviceAccountName: disco

traefik:
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesCRD: {}
    kubernetesIngress: {}
  ports:
    web:
      expose: false
    websecure:
      tls:
        enabled: true
        options: default@file
  tlsOptions:
    default:
      minVersion: VersionTLS12

cert-manager:
  installCRDs: true
  image:
    repository: keppel.global.cloud.sap/ccloud/cert-manager-controller
    tag: v1.5.5-p1
  webhook:
    image:
      repository: keppel.global.cloud.sap/ccloud-quay-mirror/jetstack/cert-manager-webhook
  cainjector:
    image:
      repository: keppel.global.cloud.sap/ccloud-quay-mirror/jetstack/cert-manager-cainjector
    extraArgs:
    - --leader-elect=false
  startupapicheck:
    image:
      repository: keppel.global.cloud.sap/ccloud-quay-mirror/jetstack/cert-manager-ctl
  ingressShim:
    defaultIssuerName: digicert-issuer
    defaultIssuerKind: DigicertIssuer
    defaultIssuerGroup: certmanager.cloud.sap
  prometheus:
    enabled: true
  podAnnotations:
    prometheus.io/targets: kubernetes

digicert-issuer:
  enableLeaderElection: "false"
