{{- if .Values.conf.log.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "cockroachdb.fullname" . }}-log-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ template "cockroachdb.chart" . }}
    app.kubernetes.io/name: {{ template "cockroachdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  log-config.yaml: {{ toYaml .Values.conf.log.config | b64enc }}
{{- end }}
