apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: k3s-litestream
  name: k3s-litestream
spec:
  selector:
    matchLabels:
      k8s-app: k3s-litestream
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: k3s-litestream
    spec:
      containers:
      - name: litestream
        image: "{{ required ".Values.images.litestream.image is missing" .Values.images.litestream.image }}:{{ required ".Values.images.litestream.tag is missing" .Values.images.litestream.tag }}"
        imagePullPolicy: IfNotPresent
        args:
          - replicate
        securityContext:
           privileged: true
        volumeMounts:
          - name: litestream-config
            mountPath: /etc/litestream.yml
            readOnly: true
      terminationGracePeriodSeconds: 5
      volumes:
        - name: litestream-config
          hostPath:
            path: "/etc/litestream.yml"
