owner-info:
  support-group: observability
  maintainers:
    - Olaf Heydorn
    - Ivo Gosemann
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/prometheus-exporters/snmp-exporter


global:
  asa:
    enabled: false
  http_sd_configs:
    netbox_url: DEFINED-IN-REGION-SECRECTS
snmp_exporter:
  image_version: "20231212095622"
  listen_port: 9116
  replicas: 2
  scrapeInterval: 1m
  scrapeTimeout: 55s
  fullnameOverride: snmp-exporter
  aggregations:
    enabled: true
    prometheus: infra-collector
  arista:
    version: 2
    community: DEFINED-IN-REGION-SECRECTS
    snmpv3:
      version: 3
      security_level: DEFINED-IN-REGION-SECRECTS
      username: DEFINED-IN-REGION-SECRECTS
      password: DEFINED-IN-REGION-SECRECTS
      auth_protocol: DEFINED-IN-REGION-SECRECTS
      priv_protocol: DEFINED-IN-REGION-SECRECTS
      priv_password: DEFINED-IN-REGION-SECRECTS
  asr:
    version: 3
    security_level: DEFINED-IN-REGION-SECRECTS
    username: DEFINED-IN-REGION-SECRECTS
    password: DEFINED-IN-REGION-SECRECTS
    auth_protocol: DEFINED-IN-REGION-SECRECTS
    priv_protocol: DEFINED-IN-REGION-SECRECTS
  asr03:
    version: 3
    security_level: DEFINED-IN-REGION-SECRECTS
    username: DEFINED-IN-REGION-SECRECTS
    password: DEFINED-IN-REGION-SECRECTS
    auth_protocol: DEFINED-IN-REGION-SECRECTS
    priv_protocol: DEFINED-IN-REGION-SECRECTS
  coreasr9k:
    version: 3
    security_level: DEFINED-IN-REGION-SECRECTS
    username: DEFINED-IN-REGION-SECRECTS
    password: DEFINED-IN-REGION-SECRECTS
    auth_protocol: DEFINED-IN-REGION-SECRECTS
    priv_protocol: DEFINED-IN-REGION-SECRECTS
  asa:
    version: 3
    security_level: DEFINED-IN-REGION-SECRECTS
    username: DEFINED-IN-REGION-SECRECTS
    password: DEFINED-IN-REGION-SECRECTS
    auth_protocol: DEFINED-IN-REGION-SECRECTS
    priv_protocol: DEFINED-IN-REGION-SECRECTS
  f5:
    version: 2
    community: DEFINED-IN-REGION-SECRECTS
    snmpv3:
      version: 3
      security_level: DEFINED-IN-REGION-SECRECTS
      username: DEFINED-IN-REGION-SECRECTS
      password: DEFINED-IN-REGION-SECRECTS
      auth_protocol: DEFINED-IN-REGION-SECRECTS
      priv_protocol: DEFINED-IN-REGION-SECRECTS
  n3k:
    version: 2
    community: DEFINED-IN-REGION-SECRECTS
  px_alerts:
    pxdl:
      enabled: false
    pxswitch:
      enabled: false
    pxswitch-multi-az:
      enabled: false
  n9kpx:
    version: 3
    security_level: DEFINED-IN-REGION-SECRECTS
    username: DEFINED-IN-REGION-SECRECTS
    password: DEFINED-IN-REGION-SECRECTS
    auth_protocol: DEFINED-IN-REGION-SECRECTS
    priv_protocol: DEFINED-IN-REGION-SECRECTS
  pxdlroutergeneric:
    version: 3
    security_level: DEFINED-IN-REGION-SECRECTS
    username: DEFINED-IN-REGION-SECRECTS
    password: DEFINED-IN-REGION-SECRECTS
    auth_protocol: DEFINED-IN-REGION-SECRECTS
    priv_protocol: DEFINED-IN-REGION-SECRECTS
  pxdlrouteriosxe:
    version: 3
    security_level: DEFINED-IN-REGION-SECRECTS
    username: DEFINED-IN-REGION-SECRECTS
    password: DEFINED-IN-REGION-SECRECTS
    auth_protocol: DEFINED-IN-REGION-SECRECTS
    priv_protocol: DEFINED-IN-REGION-SECRECTS
  pxdlrouteriosxr:
    version: 3
    security_level: DEFINED-IN-REGION-SECRECTS
    username: DEFINED-IN-REGION-SECRECTS
    password: DEFINED-IN-REGION-SECRECTS
    auth_protocol: DEFINED-IN-REGION-SECRECTS
    priv_protocol: DEFINED-IN-REGION-SECRECTS
  pxgeneric:
    version: 3
    security_level: DEFINED-IN-REGION-SECRECTS
    username: DEFINED-IN-REGION-SECRECTS
    password: DEFINED-IN-REGION-SECRECTS
    auth_protocol: DEFINED-IN-REGION-SECRECTS
    priv_protocol: DEFINED-IN-REGION-SECRECTS
  acileaf:
    version: 3
    security_level: DEFINED-IN-REGION-SECRECTS
    username: DEFINED-IN-REGION-SECRECTS
    password: DEFINED-IN-REGION-SECRECTS
    auth_protocol: DEFINED-IN-REGION-SECRECTS
    priv_protocol: DEFINED-IN-REGION-SECRECTS
  ipn:
    version: 3
    security_level: DEFINED-IN-REGION-SECRECTS
    username: DEFINED-IN-REGION-SECRECTS
    password: DEFINED-IN-REGION-SECRECTS
    auth_protocol: DEFINED-IN-REGION-SECRECTS
    priv_protocol: DEFINED-IN-REGION-SECRECTS
  acispine:
    version: 3
    security_level: DEFINED-IN-REGION-SECRECTS
    username: DEFINED-IN-REGION-SECRECTS
    password: DEFINED-IN-REGION-SECRECTS
    auth_protocol: DEFINED-IN-REGION-SECRECTS
    priv_protocol: DEFINED-IN-REGION-SECRECTS
  acistretch:
    version: 2
    community: DEFINED-IN-REGION-SECRECTS
  ucs:
    version: 3
    security_level: DEFINED-IN-REGION-SECRECTS
    username: DEFINED-IN-REGION-SECRECTS
    password: DEFINED-IN-REGION-SECRECTS
    auth_protocol: DEFINED-IN-REGION-SECRECTS
    priv_protocol: DEFINED-IN-REGION-SECRECTS
  hsm:
    version: 3
    community: DEFINED-IN-REGION-SECRECTS
    security_level: DEFINED-IN-REGION-SECRECTS
    username: DEFINED-IN-REGION-SECRECTS
    password: DEFINED-IN-REGION-SECRECTS
    auth_protocol: DEFINED-IN-REGION-SECRECTS
    priv_protocol: DEFINED-IN-REGION-SECRECTS
  aristaevpn:
    version: 3
    community: DEFINED-IN-REGION-SECRECTS
    security_level: DEFINED-IN-REGION-SECRECTS
    username: DEFINED-IN-REGION-SECRECTS
    password: DEFINED-IN-REGION-SECRECTS
    auth_protocol: DEFINED-IN-REGION-SECRECTS
    priv_protocol: DEFINED-IN-REGION-SECRECTS
  aristaspine:
    version: 3
    community: DEFINED-IN-REGION-SECRECTS
    security_level: DEFINED-IN-REGION-SECRECTS
    username: DEFINED-IN-REGION-SECRECTS
    password: DEFINED-IN-REGION-SECRECTS
    auth_protocol: DEFINED-IN-REGION-SECRECTS
    priv_protocol: DEFINED-IN-REGION-SECRECTS
  fortinet:
    version: 3
    security_level: DEFINED-IN-REGION-SECRECTS
    username: DEFINED-IN-REGION-SECRECTS
    password: DEFINED-IN-REGION-SECRECTS
    auth_protocol: DEFINED-IN-REGION-SECRECTS
    priv_protocol: DEFINED-IN-REGION-SECRECTS
  alerts:
    enabled: false
    prometheus: DEFINED-IN-REGION-SECRETS
