owner-info:
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/openstack/manila-nanny
  service: manila
  support-group: compute-storage-api
  maintainers:
    - Maurice Escher
    - Chuan Miao

# debug mode - no script run in the containers, just a sleep loop
debug: false

image:
  name: manila-nanny
  version: latest

dependencyService: manila-mariadb,manila-api

sentry:
  enabled: true

netapp:
  username: manilananny
  password: DEFINED_IN_SECRETS

# interval and resources can be overriden by each nanny
interval: 3600

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"

nannies:
  db_purge:
    enabled: true
    dry_run: false
    # purge deleted db entries older than n days
    older_than: 14

  consistency:
    enabled: true
    dry_run: false

  quota_sync:
    enabled: true
    dry_run: false
    resources:
      requests:
        memory: "64Mi"
        cpu: "300m"

  share_sync:
    enabled: true
    dry_run: false
    task_share_size: true
    task_share_size_dry_run: false
    task_missing_volume: true
    task_missing_volume_dry_run: false
    task_offline_volume: true
    task_offline_volume_dry_run: false
    task_orphan_volume: true
    task_orphan_volume_dry_run: false
    task_share_state: true
    task_share_state_dry_run: true # do not reset share state automatically
    http_port: 8002
    prometheus_port: 9502

  share_server:
    enabled: true
    listen_port: 8000
    prometheus_port: 9500

  snapshot:
    enabled: true
    listen_port: 8001
    prometheus_port: 9501
    task_share_snapshot_state: true
    task_share_snapshot_state_dry_run: false

  snapshot_missing:
    enabled: true
    interval: 1800
    prometheus_port: 9503

  db_cleanup:
    enabled: true
    dry_run: false

