qalogs:
  enabled: false

opensearch_master:
  nameOverride: "opensearch-logs-master"
  fullnameOverride: "opensearch-logs-master"
  nodeGroup: "master"
  masterService: "opensearch-logs-master"
  roles:
    - master
  replicas: 3
  opensearchJavaOpts: "-Dlog4j2.formatMsgNoLookups=true -XX:MaxRAM=5g -XX:MaxGCPauseMillis=5000"
  persistence:
    enabled: true
    enableInitChown: true
    size: 1Gi
    image: "library/busybox"
  clusterName: "opensearch-logs"
  secretMounts:
    - name: opensearch-certificates
      secretName: opensearch-certs
      path: /usr/share/opensearch/config/certs/
      defaultMode: 0644
  securityConfig:
    enabled: true
    config:
      securityConfigSecret: "security-config"
  extraEnvs:
    - name: DISABLE_INSTALL_DEMO_CONFIG
      value: "true"

opensearch_client:
  nameOverride: "opensearch-logs-client"
  fullnameOverride: "opensearch-logs-client"
  nodeGroup: "client"
  masterService: "opensearch-logs-master"
  roles:
    - remote_cluster_client
  replicas: 2
  opensearchJavaOpts: "-Dlog4j2.formatMsgNoLookups=true -XX:MaxRAM=5g -XX:MaxGCPauseMillis=5000 -Xms1g -Xmx1g"
  secretMounts:
    - name: opensearch-certificates
      secretName: opensearch-certs
      path: /usr/share/opensearch/config/certs/
      defaultMode: 0644
  persistence:
    enabled: false
    enableInitChown: false
    image: "library/busybox"
  service:
    type: LoadBalancer
  ingress:
    enabled: false
  clusterName: "opensearch-logs"

  securityConfig:
    config:
      securityConfigSecret: "security-config"
  extraEnvs:
    - name: DISABLE_INSTALL_DEMO_CONFIG
      value: "true"

opensearch_data:
  nameOverride: "opensearch-logs-data"
  fullnameOverride: "opensearch-logs-data"
  nodeGroup: "data"
  masterService: "opensearch-logs-master"
  roles:
    - ingest
    - data
  replicas: 3
  opensearchJavaOpts: "-Dlog4j2.formatMsgNoLookups=true -XX:MaxRAM=7g -XX:MaxGCPauseMillis=500 -Xms5g -Xmx5g"
  persistence:
    enabled: true
    enableInitChown: true
    size: 500Gi
    image: "library/busybox"
  clusterName: "opensearch-logs"
  secretMounts:
    - name: opensearch-certificates
      secretName: opensearch-certs
      path: /usr/share/opensearch/config/certs/
      defaultMode: 0644

  securityConfig:
    config:
      securityConfigSecret: "security-config"
  extraEnvs:
    - name: DISABLE_INSTALL_DEMO_CONFIG
      value: "true"


opensearch_dashboards:
  serviceAccount:
    create: true
    name: "opensearch-logs-dashboards"
  config:
    opensearch_dashboards.yml: |
      server:
        name: dashboards
        host: 0.0.0.0
        ssl:
          enabled: false


  ingress:
    enabled: false
 
