apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: clair-api
  annotations:
    kubernetes.io/tls-acme: "true"
    disco: "true"

spec:
  tls:
     - secretName: tls-clair
       hosts: [keppel-clair.{{.Values.global.region}}.{{.Values.global.tld}}]
  rules:
    - host: keppel-clair.{{.Values.global.region}}.{{.Values.global.tld}}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: clair
              port:
                number: 8080
