apiVersion: v1
kind: Service

metadata:
  name: clair-indexer
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/targets: "openstack"

spec:
  selector:
    name: clair-indexer
  ports:
    - name: api
      port: 8080
    - name: introspection
      port: 8081
