# Default values for cloudprober.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
enabled: false

image:
  name: cloudprober # cloudprober/cloudprober
  tag: test4 # custom build to fix icmp ssue in v0.11.6
  pullPolicy: IfNotPresent

fullnameOverride: cloudprober-exporter
replicaCount: 1
revisionHistoryLimit: 5

metrics:
  scrape: true
  port: 9313
  prometheus: infra-collector

ingress:
  tls: true
  disco: true
  hostName_prefix: cloudprober

icmpIntervalMsec: 5000  # 5s
icmpTimeoutMsec: 3000   # 3s
httpIntervalMsec: 5000  # 5s
httpTimeoutMsec: 3000   # 3s

probers:
  - DEFINED-IN-REGIONS-SECRETS

targets_icmp:
# qa-de-1 -------------------------
  - name: cc3test-admin-jump-qade1a
    ip: 10.237.208.56
    dns: jump-qade1a.cc3test-admin.c.qa-de-1.cloud.sap
    dc: qa-de-1a
  - name: cc3test-admin-jump-qade1b
    ip: 10.237.208.91
    dns: jump-qade1b.cc3test-admin.c.qa-de-1.cloud.sap
    dc: qa-de-1b
  - name: cc3test-test-jump-qade1a
    ip: 10.237.208.9
    dns: jump-qade1a.cc3test-test.c.qa-de-1.cloud.sap
    dc: qa-de-1a
  - name: cc3test-test-jump-qade1b
    ip: 10.237.208.147
    dns: jump-qade1b.cc3test-test.c.qa-de-1.cloud.sap
    dc: qa-de-1b
  - name: cc3test-regression-jump-qade1a
    ip: 10.237.208.196
    dns: jump-qade1a.cc3test-regression.c.qa-de-1.cloud.sap
    dc: qa-de-1a
  - name: cc3test-regression-jump-qade1b
    ip: 10.237.208.183
    dns: jump-qade1b.cc3test-regression.c.qa-de-1.cloud.sap
    dc: qa-de-1b
  - name: cloudprober-1a
    ip: 10.46.101.213
    dc: qa-de-1a
  - name: cloudrober-1b
    ip: 10.46.101.214
    dc: qa-de-1b
# ap-jp-2 -------------------------
  - name: cc3test-admin-jump-apjp2a
    ip: 10.236.16.71
    dns: jump-apjp2a.cc3test-admin.c.ap-jp-2.cloud.sap
    dc: ap-jp-2a
  - name: cc3test-test-jump-apjp2a
    ip: 10.236.16.67
    dns: jump-apjp2a.cc3test-test.c.ap-jp-2.cloud.sap
    dc: ap-jp-2a
  - name: cc3test-regression-jump-apjp2a
    ip: 10.236.16.74
    dns: jump-apjp2a.cc3test-regression.c.ap-jp-2.cloud.sap
    dc: ap-jp-2a
# ap-sa-2 -------------------------
  - name: cc3test-admin-jump-apsa2a
    ip: 10.237.216.168
    dns: jump-apsa2a.cc3test-admin.c.ap-sa-2.cloud.sap
    dc: ap-sa-2a
  - name: cc3test-test-jump-apsa2a
    ip: 10.237.216.178
    dns: jump-apsa2a.cc3test-test.c.ap-sa-2.cloud.sap
    dc: ap-sa-2a
  - name: cc3test-regression-jump-apsa2a
    ip: 10.237.217.216
    dns: jump-apsa2a.cc3test-regression.c.ap-sa-2.cloud.sap
    dc: ap-sa-2a
# na-ca-1 -------------------------
  - name: cc3test-admin-jump-naca1a
    ip: 10.47.161.98
    dns: jump-naca1a.cc3test-admin.c.na-ca-1.cloud.sap
    dc: na-ca-1a
  - name: cc3test-admin-jump-naca1b
    ip: 10.47.161.124
    dns: jump-naca1b.cc3test-admin.c.na-ca-1.cloud.sap
    dc: na-ca-1b
  - name: cc3test-test-jump-naca1a
    ip: 10.47.161.97
    dns: jump-naca1a.cc3test-test.c.na-ca-1.cloud.sap
    dc: na-ca-1a
  - name: cc3test-test-jump-naca1b
    ip: 10.47.161.45
    dns: jump-naca1b.cc3test-test.c.na-ca-1.cloud.sap
    dc: na-ca-1b
  - name: cc3test-regression-jump-naca1a
    ip: 10.47.160.113
    dns: jump-naca1a.cc3test-regression.c.na-ca-1.cloud.sap
    dc: na-ca-1a
  - name: cc3test-regression-jump-naca1b
    ip: 10.47.161.73
    dns: jump-naca1b.cc3test-regression.c.na-ca-1.cloud.sap
    dc: na-ca-1b
# na-us-3 -------------------------
  - name: cc3test-admin-jump-naus3a
    ip: 10.47.104.83
    dns: jump-naus3a.cc3test-admin.c.na-us-3.cloud.sap
    dc: na-us-3a
  - name: cc3test-test-jump-naus3a
    ip: 10.47.106.107
    dns: jump-naus3a.cc3test-test.c.na-us-3.cloud.sap
    dc: na-us-3a
  - name: cc3test-regression-jump-naus3a
    ip: 10.47.106.131
    dns: jump-naus3a.cc3test-regression.c.na-us-3.cloud.sap
    dc: na-us-3a

targets_http:
  - DEFINED-IN-REGIONS-SECRETS