kind: Deployment
apiVersion: apps/v1

metadata:
  name: tenso-api

spec:
  revisionHistoryLimit: 5
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      name: tenso-api
  selector:
    matchLabels:
      name: tenso-api
  template:
    metadata:
      labels:
        name: tenso-api
        alert-tier: os
        alert-service: tenso
      annotations:
        checksum/secret: {{ include "tenso/templates/secret.yaml" . | sha256sum }}
    spec:
      containers:
        - name: api
          image: {{ include "tenso_image" $ }}
          imagePullPolicy: IfNotPresent
          args: [ api ]
          env: {{ include "tenso_environment" $ | indent 12 }}
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            timeoutSeconds: 10
            periodSeconds: 60
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            timeoutSeconds: 5
            periodSeconds: 5
          resources:
            # TODO: adjust once we have some operating experience
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
