apiVersion: v1
kind: Secret
metadata:
  name: tenso-secret
data:
  service_user_password: {{ required ".Values.tenso.service_password is missing" .Values.tenso.service_password | b64enc }}
  postgres_password: {{ required ".Values.postgresql.postgresPassword is missing" .Values.postgresql.postgresPassword | b64enc }}
