kind: Service
apiVersion: v1

metadata:
  name: tenso-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/targets: {{ .Values.prometheus.targets.openstack }}

spec:
  selector:
    name: tenso-api
  ports:
    - port: 80
