global:
  registry: myRegistry
  dbPassword: secret!
  master_password: topSecret!
  octavia_service_password: topSecret!!

imageVersion: train

mariadb:
  root_password: topSecret
  backup_v2:
    enabled: false

rabbitmq:
  metrics:
    enabled: false
  users:
    default:
      password: defaultpass
    admin:
      password: adminpass

rabbitmq_notifications:
  metrics:
    enabled: false
  users:
    default:
      password: defaultpass
    admin:
      password: adminpass
