apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: andromeda
  labels:
{{ include "andromeda.labels" . | indent 4 }}
  name: endpoint-reader
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
