{{- if and .Values.backup.enabled .Values.backup.claimName }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "fullName" . }}-{{ .Values.backup.claimName }}
spec:
{{- if .Values.persistence_claim.access_modes }}
  accessModes:
  {{- range $accessMode := .Values.persistence_claim.access_modes }}
  - {{ $accessMode }}
  {{- end }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence_claim.size }}
  {{- if .Values.persistence_claim.storage_class }}
  storageClassName: .Values.persistence_claim.storage_class
  {{- end }}
{{ end }}
