{{- if and .Values.backup.enabled .Values.backup.claimName }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "fullName" . }}-{{ .Values.backup.claimName }}
spec:
{{- if .Values.persistence.accessMode }}
  accessModes:
  {{- range $access_mode := .Values.persistence.accessMode }}
  - {{ $access_mode }}
  {{- end }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: .Values.persistence.storage_class
  {{- end }}
{{ end }}
