{{- if .Values.metis.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metis
  namespace: {{ .Values.namespace }}
  labels:
    prometheus: {{ .Values.alerts.prometheus }}
spec:
  jobLabel: metis
  selector:
    matchLabels:
      app.kubernetes.io/name: metis
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  podMetricsEndpoints:
    - interval: 60s
      scrapeTimeout: 55s
      port: metrics
      path: {{ .Values.metis.metrics.path }}
      relabelings:
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)

{{- end }}
