{{- if .Values.metisAPI.enabled }}

apiVersion: v1
kind: Service
metadata:
  name:  metis-api
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: metis
    helm.sh/chart: {{ include "metis.chart" $ }}
    app.kubernetes.io/instance: metis-{{ .Release.Name }}
    app.kubernetes.io/component: "api"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/component: "api"
  ports:
  - name: http
    port: {{ .Values.metisAPI.port }}
    protocol: TCP

{{- end }}
