{{- if .Values.metis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: metis-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: metis
    helm.sh/chart: {{ include "metis.chart" $ }}
    app.kubernetes.io/instance: metis-{{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  metisAdminPW: {{ required "missing MetisDB root pw" .Values.mariadb.root_password }}
  metisRonlyPW: {{ required "missing MetisDB ronly pw" .Values.global.metis.password }}
  billingToken: {{ required "missing billing API token" .Values.metis.billingApiToken }}
  ldapBindPW: {{ required "missing LDAP bind pw" .Values.metisAPI.ldap.password }}
  ronlyUser: {{ required "missing basic user" .Values.metisAPI.basic.user }}
  ronlyPW: {{ required "missing basic pw" .Values.metisAPI.basic.password }}


{{- end }}
