{{- if .Values.metisSync.alerts.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metis-sync
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: mariadb-sync
    helm.sh/chart: {{ include "metis.chart" $ }}
    app.kubernetes.io/instance: mariadb-sync
    app.kubernetes.io/component: "replication"
    app.kubernetes.io/part-of: "metis"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    prometheus: {{ .Values.alerts.prometheus }}
spec:
  jobLabel: metis
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb-sync
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  podMetricsEndpoints:
    - interval: 60s
      scrapeTimeout: 55s
      port: metrics
      path: "/metrics"
{{- end }}
