{{- if .Values.enabled }}
{{- $root := . }}
{{- range $name := coalesce .Values.names .Values.global.targets (list .Values.name) }}
{{- if $.Values.deployWholeThanos }} 
{{- range $component := tuple "compactor" "query" "store" }}
{{- $path := (printf "%s/alerts/_thanos-%s.alerts.tpl" $root.Template.BasePath $component ) }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: {{ include "thanos.fullName" (list $name $root) }}-{{ printf "%s" $component }}.alerts
  labels:
    prometheus: {{ default (include "thanos.name" (list $name $root)) $.Values.alerts.prometheus }}

spec:
{{ include $path (list $name $root) | indent 2 }}

{{- end }}
{{- else }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: {{ include "thanos.fullName" (list $name $root) }}-query.alerts
  labels:
    prometheus: {{ required "$.Values.alerts.prometheus" $.Values.alerts.prometheus }}

spec:
{{ include (print $.Template.BasePath "/alerts/_thanos-query.alerts.tpl") (list $name $root) | indent 2 }}

{{- end }}
{{- end }}
{{- end }}
