{{- if .Values.enabled }}
{{- $root := . }}
{{- range $name := coalesce .Values.names .Values.global.targets (list .Values.name) }}
{{- range $component := tuple "compactor" "query" "store" }}
{{- $path := (printf "%s/alerts/_thanos-%s.alerts.tpl" $root.Template.BasePath $component ) }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: {{ include "thanos.fullName" (list $name $root) }}-{{ printf "%s" $component }}.alerts
  labels:
    {{- if $root.Values.deployWholeThanos }}
    prometheus: {{ default (include "thanos.name" (list $name $root)) $.Values.alerts.prometheus }}
    {{- else }}
    prometheus: {{ required "$.Values.alerts.prometheus" $.Values.alerts.prometheus }}
    {{- end }}

spec:
{{ include $path (list $name $root) | indent 2 }}

{{- end }}
{{- end }}
{{- end }}
