apiVersion: v1
kind: Secret

metadata:
  name: opensearch-certs

data:
  opensearchCA.key: {{ required ".Values.global.ca missing" .Values.global.ca | b64enc | quote }}
  wildcard-tp-opensearch.key: {{ required ".Values.global.tp.key missing" .Values.global.tp.key | b64enc | quote }}
  wildcard-tp-opensearch.crt: {{ required ".Values.global.tp.crt missing" .Values.global.tp.crt | b64enc | quote }}
