kubernikus:
  imageTag: 84912b2be11d8d7019034e78c615bc89355e0996
  image: keppel.global.cloud.sap/ccloud/kubernikus

  #use a dedicated serviceaccount and proper RBAC rules for this deployment
  standalone: false
  useServiceAccount: true
  includeRBAC: true
  k8sniff:
    useRBAC: true

  api:
    policyFile: /etc/kubernikus/policy-ccadmin.json
  operator:
    nodeAffinity: false
  ingress:
    annotations:
      disco: "true"
kubernikus-dex:
  namespaceOverride: kubernikus
