apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: andromeda
version: 0.1.0
dependencies:
  - name: postgresql
    condition: postgresql.enabled
    repository: file://../../common/postgresql
    version: 0.3.0

