apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-exporter
data:
  snmp-exporter.yaml: |
    auths:
      aas_v3:
        version: {{ .Values.snmp_exporter.arista.snmpv3.version }}
        security_level: {{ .Values.snmp_exporter.arista.snmpv3.security_level }}
        username: {{ .Values.snmp_exporter.arista.snmpv3.username }}
        password: {{ .Values.snmp_exporter.arista.snmpv3.password }}
        auth_protocol: {{ .Values.snmp_exporter.arista.snmpv3.auth_protocol }}
        priv_protocol: {{ .Values.snmp_exporter.arista.snmpv3.priv_protocol }}
        priv_password: {{ .Values.snmp_exporter.arista.snmpv3.priv_password }}
    modules:
{{ .Files.Get "_snmp-exporter-aas.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-ams.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-asa.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-asr.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-f5customer.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-f5mgmt.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-f5gtm.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-f5archer.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-f5physical.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-asr03.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-coreasr9k.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-n3k.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-pxgeneric.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-pxdlroutergeneric.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-pxdlrouteriosxe.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-pxdlrouteriosxr.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-acileaf.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-n9kpx.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-ipn.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-acispine.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-acistretch.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-ucs.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-hsm.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-aristaevpn.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-aristaspine.yaml" | indent 4}}
{{ .Files.Get "_snmp-exporter-fortinet.yaml" | indent 4}}
