{{- if .Values.ingress.enabled }}
{{- $root := . }}
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ include "prometheus.fullName" . }}
  labels:
    prometheus: {{ include "prometheus.name" . }}
  annotations:
    kubernetes.io/tls-acme: "true"
    disco: "true"
    {{- if .Values.ingress.authentication.oauth.enabled }}
    ingress.kubernetes.io/auth-url: {{ required ".Values.ingress.authentication.oauth.authURL missing" .Values.ingress.authentication.oauth.authURL }}
    {{ if .Values.ingress.authentication.oauth.authSignInURL }}ingress.kubernetes.io/auth-signin: {{ .Values.ingress.authentication.oauth.authSignInURL }} {{ end }}
    {{ end }}
    {{- if .Values.ingress.authentication.sso.enabled}}
    ingress.kubernetes.io/auth-tls-secret: {{ required ".Values.ingress.authentication.sso.authTLSSecret missing" .Values.ingress.authentication.sso.authTLSSecret | quote }}
    ingress.kubernetes.io/auth-tls-verify-depth: {{ required ".Values.ingress.authentication.sso.authTLSVerifyDepth missing" .Values.ingress.authentication.sso.authTLSVerifyDepth | quote }}
    ingress.kubernetes.io/auth-tls-verify-client: {{ required ".Values.ingress.authentication.sso.authTLSVerifyClient missing" .Values.ingress.authentication.sso.authTLSVerifyClient | quote }}
    {{ end }}
    {{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
    {{ end }}

spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ include "fqdnHelper" (list $host $root) }}
      http:
        paths:
        - path: /
          backend:
            service:
              name: {{ include "prometheus.fullName" $root }}
              port:
                name: http
        {{- if $root.Values.thanos.enabled }}
        - path: {{ required ".Values.thanos.querier.webRouteprefix missing" $root.Values.thanos.querier.webRouteprefix }}
          backend:
            service:
              name: {{ include "prometheus.fullName" $root }}-thanos-query
              port:
                name: http
        {{- end }}
    {{- end }}
    {{- range $host := .Values.ingress.hostsFQDN }}
    - host: {{ $host }}
      http:
        paths:
        - path: /
          backend:
            service:
              name: {{ include "prometheus.fullName" $root }}
              port:
                name: http
        {{- if $root.Values.thanos.enabled }}
        - path: {{ required ".Values.thanos.querier.webRouteprefix missing" $root.Values.thanos.querier.webRouteprefix }}
          backend:
            service:
              name: {{ include "prometheus.fullName" $root }}-thanos-query
              port:
                name: http
        {{- end }}
    {{- end }}
  tls:
    - secretName: tls-{{ include "prometheus.externalURL" $root | replace "." "-" }}
      hosts:
        {{- range $host := .Values.ingress.hosts }}
        - {{ include "fqdnHelper" (list $host $root) }}
        {{- end }}
        {{- range $host := .Values.ingress.hostsFQDN }}
        - {{ $host }}
        {{- end }}
{{- end }}
