{{- if .Values.scaleout.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-cert-manager
  namespace: opensearch-logs
spec:
  dnsNames:
  - 'OpensearchAdmin-{{ .Values.global.clusterType }}.{{ .Values.global.region }}.cloud.sap'
  issuerRef:
    group: certmanager.cloud.sap
    kind: DigicertIssuer
    name: digicert-issuer
  secretName: admin-cert-manager
{{- end }}
