{{- if .Values.scaleout.enabled }}
apiVersion: v1
kind: Secret

metadata:
  name: admin-cert

data:
  opensearchCA.crt: {{ required ".Values.ca.crt missing" .Values.ca.crt | quote }}
  admin.crt: {{ required ".Values.admin.crt missing" .Values.admin.crt | quote }}
  admin.pem: {{ required ".Values.admin.pem missing" .Values.admin.pem | quote }}
{{- end }}
