apiVersion: v1
kind: Secret
metadata:
  name: kibana-objecter-secret
type: Opaque
stringData:
  KIBANA_API_TOKEN: "{{ .Values.kibanaObjecter.kibana_api_token }}"
  GIT_TOKEN: "{{ .Values.kibanaObjecter.git_token }}"